package shared

import "github.com/overmindtech/cli/sources/shared"

// Item types for Azure resources
// These combine the Azure source, API (resource provider), and resource type
// to create unique item type identifiers following the pattern: azure-{api}-{resource}
var (
	// Compute item types
	ComputeVirtualMachine                  = shared.NewItemType(Azure, Compute, VirtualMachine)
	ComputeDisk                            = shared.NewItemType(Azure, Compute, Disk)
	ComputeAvailabilitySet                 = shared.NewItemType(Azure, Compute, AvailabilitySet)
	ComputeVirtualMachineExtension         = shared.NewItemType(Azure, Compute, VirtualMachineExtension)
	ComputeVirtualMachineRunCommand        = shared.NewItemType(Azure, Compute, VirtualMachineRunCommand)
	ComputeVirtualMachineScaleSet          = shared.NewItemType(Azure, Compute, VirtualMachineScaleSet)
	ComputeDiskEncryptionSet               = shared.NewItemType(Azure, Compute, DiskEncryptionSet)
	ComputeProximityPlacementGroup         = shared.NewItemType(Azure, Compute, ProximityPlacementGroup)
	ComputeDedicatedHostGroup              = shared.NewItemType(Azure, Compute, DedicatedHostGroup)
	ComputeCapacityReservationGroup        = shared.NewItemType(Azure, Compute, CapacityReservationGroup)
	ComputeImage                           = shared.NewItemType(Azure, Compute, Image)
	ComputeSnapshot                        = shared.NewItemType(Azure, Compute, Snapshot)
	ComputeDiskAccess                      = shared.NewItemType(Azure, Compute, DiskAccess)
	ComputeSharedGalleryImage              = shared.NewItemType(Azure, Compute, SharedGalleryImage)
	ComputeCommunityGalleryImage           = shared.NewItemType(Azure, Compute, CommunityGalleryImage)
	ComputeSharedGalleryApplicationVersion = shared.NewItemType(Azure, Compute, SharedGalleryApplicationVersion)

	// Network item types
	NetworkVirtualNetwork                                 = shared.NewItemType(Azure, Network, VirtualNetwork)
	NetworkSubnet                                         = shared.NewItemType(Azure, Network, Subnet)
	NetworkNetworkInterface                               = shared.NewItemType(Azure, Network, NetworkInterface)
	NetworkPublicIPAddress                                = shared.NewItemType(Azure, Network, PublicIPAddress)
	NetworkNetworkSecurityGroup                           = shared.NewItemType(Azure, Network, NetworkSecurityGroup)
	NetworkVirtualNetworkPeering                          = shared.NewItemType(Azure, Network, VirtualNetworkPeering)
	NetworkNetworkInterfaceIPConfiguration                = shared.NewItemType(Azure, Network, NetworkInterfaceIPConfiguration)
	NetworkPrivateEndpoint                                = shared.NewItemType(Azure, Network, PrivateEndpoint)
	NetworkLoadBalancer                                   = shared.NewItemType(Azure, Network, LoadBalancer)
	NetworkLoadBalancerFrontendIPConfiguration            = shared.NewItemType(Azure, Network, LoadBalancerFrontendIPConfiguration)
	NetworkLoadBalancerBackendAddressPool                 = shared.NewItemType(Azure, Network, LoadBalancerBackendAddressPool)
	NetworkLoadBalancerInboundNatRule                     = shared.NewItemType(Azure, Network, LoadBalancerInboundNatRule)
	NetworkLoadBalancerLoadBalancingRule                  = shared.NewItemType(Azure, Network, LoadBalancerLoadBalancingRule)
	NetworkLoadBalancerProbe                              = shared.NewItemType(Azure, Network, LoadBalancerProbe)
	NetworkLoadBalancerOutboundRule                       = shared.NewItemType(Azure, Network, LoadBalancerOutboundRule)
	NetworkLoadBalancerInboundNatPool                     = shared.NewItemType(Azure, Network, LoadBalancerInboundNatPool)
	NetworkPublicIPPrefix                                 = shared.NewItemType(Azure, Network, PublicIPPrefix)
	NetworkNatGateway                                     = shared.NewItemType(Azure, Network, NatGateway)
	NetworkDdosProtectionPlan                             = shared.NewItemType(Azure, Network, DdosProtectionPlan)
	NetworkApplicationGateway                             = shared.NewItemType(Azure, Network, ApplicationGateway)
	NetworkApplicationGatewayBackendAddressPool           = shared.NewItemType(Azure, Network, ApplicationGatewayBackendAddressPool)
	NetworkApplicationGatewayFrontendIPConfiguration      = shared.NewItemType(Azure, Network, ApplicationGatewayFrontendIPConfiguration)
	NetworkApplicationGatewayGatewayIPConfiguration       = shared.NewItemType(Azure, Network, ApplicationGatewayGatewayIPConfiguration)
	NetworkApplicationGatewayHTTPListener                 = shared.NewItemType(Azure, Network, ApplicationGatewayHTTPListener)
	NetworkApplicationGatewayBackendHTTPSettings          = shared.NewItemType(Azure, Network, ApplicationGatewayBackendHTTPSettings)
	NetworkApplicationGatewayRequestRoutingRule           = shared.NewItemType(Azure, Network, ApplicationGatewayRequestRoutingRule)
	NetworkApplicationGatewayProbe                        = shared.NewItemType(Azure, Network, ApplicationGatewayProbe)
	NetworkApplicationGatewaySSLCertificate               = shared.NewItemType(Azure, Network, ApplicationGatewaySSLCertificate)
	NetworkApplicationGatewayURLPathMap                   = shared.NewItemType(Azure, Network, ApplicationGatewayURLPathMap)
	NetworkApplicationGatewayAuthenticationCertificate    = shared.NewItemType(Azure, Network, ApplicationGatewayAuthenticationCertificate)
	NetworkApplicationGatewayTrustedRootCertificate       = shared.NewItemType(Azure, Network, ApplicationGatewayTrustedRootCertificate)
	NetworkApplicationGatewayRewriteRuleSet               = shared.NewItemType(Azure, Network, ApplicationGatewayRewriteRuleSet)
	NetworkApplicationGatewayRedirectConfiguration        = shared.NewItemType(Azure, Network, ApplicationGatewayRedirectConfiguration)
	NetworkApplicationGatewayWebApplicationFirewallPolicy = shared.NewItemType(Azure, Network, ApplicationGatewayWebApplicationFirewallPolicy)
	NetworkApplicationSecurityGroup                       = shared.NewItemType(Azure, Network, ApplicationSecurityGroup)
	NetworkSecurityRule                                   = shared.NewItemType(Azure, Network, SecurityRule)
	NetworkDefaultSecurityRule                            = shared.NewItemType(Azure, Network, DefaultSecurityRule)
	NetworkIPGroup                                        = shared.NewItemType(Azure, Network, IPGroup)
	NetworkRouteTable                                     = shared.NewItemType(Azure, Network, RouteTable)
	NetworkRoute                                          = shared.NewItemType(Azure, Network, Route)
	NetworkVirtualNetworkGateway                          = shared.NewItemType(Azure, Network, VirtualNetworkGateway)
	NetworkPrivateDNSZone                                 = shared.NewItemType(Azure, Network, PrivateDNSZone)
	NetworkZone                                           = shared.NewItemType(Azure, Network, Zone)
	NetworkDNSRecordSet                                   = shared.NewItemType(Azure, Network, DNSRecordSet)
	NetworkDNSVirtualNetworkLink                          = shared.NewItemType(Azure, Network, DNSVirtualNetworkLink)

	//Storage item types
	StorageAccount       = shared.NewItemType(Azure, Storage, Account)
	StorageBlobContainer = shared.NewItemType(Azure, Storage, BlobContainer)
	StorageFileShare     = shared.NewItemType(Azure, Storage, FileShare)
	StorageTable         = shared.NewItemType(Azure, Storage, Table)
	StorageQueue         = shared.NewItemType(Azure, Storage, Queue)

	// SQL item types
	SQLDatabase                              = shared.NewItemType(Azure, SQL, Database)
	SQLRecoverableDatabase                   = shared.NewItemType(Azure, SQL, RecoverableDatabase)
	SQLRecoveryServicesRecoveryPoint         = shared.NewItemType(Azure, SQL, RecoveryServicesRecoveryPoint)
	SQLRestorableDroppedDatabase             = shared.NewItemType(Azure, SQL, RestorableDroppedDatabase)
	SQLServer                                = shared.NewItemType(Azure, SQL, Server)
	SQLElasticPool                           = shared.NewItemType(Azure, SQL, ElasticPool)
	SQLServerFirewallRule                    = shared.NewItemType(Azure, SQL, ServerFirewallRule)
	SQLServerVirtualNetworkRule              = shared.NewItemType(Azure, SQL, ServerVirtualNetworkRule)
	SQLServerKey                             = shared.NewItemType(Azure, SQL, ServerKey)
	SQLServerFailoverGroup                   = shared.NewItemType(Azure, SQL, ServerFailoverGroup)
	SQLServerAdministrator                   = shared.NewItemType(Azure, SQL, ServerAdministrator)
	SQLServerSyncGroup                       = shared.NewItemType(Azure, SQL, ServerSyncGroup)
	SQLServerSyncAgent                       = shared.NewItemType(Azure, SQL, ServerSyncAgent)
	SQLServerPrivateEndpointConnection       = shared.NewItemType(Azure, SQL, ServerPrivateEndpointConnection)
	SQLServerAuditingSetting                 = shared.NewItemType(Azure, SQL, ServerAuditingSetting)
	SQLServerSecurityAlertPolicy             = shared.NewItemType(Azure, SQL, ServerSecurityAlertPolicy)
	SQLServerVulnerabilityAssessment         = shared.NewItemType(Azure, SQL, ServerVulnerabilityAssessment)
	SQLServerEncryptionProtector             = shared.NewItemType(Azure, SQL, ServerEncryptionProtector)
	SQLServerBlobAuditingPolicy              = shared.NewItemType(Azure, SQL, ServerBlobAuditingPolicy)
	SQLServerAutomaticTuning                 = shared.NewItemType(Azure, SQL, ServerAutomaticTuning)
	SQLServerAdvancedThreatProtectionSetting = shared.NewItemType(Azure, SQL, ServerAdvancedThreatProtectionSetting)
	SQLServerDnsAlias                        = shared.NewItemType(Azure, SQL, ServerDnsAlias)
	SQLServerUsage                           = shared.NewItemType(Azure, SQL, ServerUsage)
	SQLServerOperation                       = shared.NewItemType(Azure, SQL, ServerOperation)
	SQLServerAdvisor                         = shared.NewItemType(Azure, SQL, ServerAdvisor)
	SQLServerBackupLongTermRetentionPolicy   = shared.NewItemType(Azure, SQL, ServerBackupLongTermRetentionPolicy)
	SQLServerDevOpsAuditSetting              = shared.NewItemType(Azure, SQL, ServerDevOpsAuditSetting)
	SQLServerTrustGroup                      = shared.NewItemType(Azure, SQL, ServerTrustGroup)
	SQLServerOutboundFirewallRule            = shared.NewItemType(Azure, SQL, ServerOutboundFirewallRule)
	SQLServerPrivateLinkResource             = shared.NewItemType(Azure, SQL, ServerPrivateLinkResource)

	// DBforPostgreSQL item types
	DBforPostgreSQLFlexibleServer                          = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServer)
	DBforPostgreSQLDatabase                                = shared.NewItemType(Azure, DBforPostgreSQL, Database)
	DBforPostgreSQLFlexibleServerFirewallRule              = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerFirewallRule)
	DBforPostgreSQLFlexibleServerConfiguration             = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerConfiguration)
	DBforPostgreSQLFlexibleServerAdministrator             = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerAdministrator)
	DBforPostgreSQLFlexibleServerPrivateEndpointConnection = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerPrivateEndpointConnection)
	DBforPostgreSQLFlexibleServerPrivateLinkResource       = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerPrivateLinkResource)
	DBforPostgreSQLFlexibleServerReplica                   = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerReplica)
	DBforPostgreSQLFlexibleServerMigration                 = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerMigration)
	DBforPostgreSQLFlexibleServerBackup                    = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerBackup)
	DBforPostgreSQLFlexibleServerVirtualEndpoint           = shared.NewItemType(Azure, DBforPostgreSQL, FlexibleServerVirtualEndpoint)

	// DocumentDB item types
	DocumentDBDatabaseAccounts          = shared.NewItemType(Azure, DocumentDB, DatabaseAccounts)
	DocumentDBPrivateEndpointConnection = shared.NewItemType(Azure, DocumentDB, PrivateEndpointConnection)

	// KeyVault item types
	KeyVaultVault      = shared.NewItemType(Azure, KeyVault, Vault)
	KeyVaultSecret     = shared.NewItemType(Azure, KeyVault, Secret)
	KeyVaultKey        = shared.NewItemType(Azure, KeyVault, Key)
	KeyVaultManagedHSM = shared.NewItemType(Azure, KeyVault, ManagedHSM)

	// ManagedIdentity item types
	ManagedIdentityUserAssignedIdentity = shared.NewItemType(Azure, ManagedIdentity, UserAssignedIdentity)

	// Batch item types
	BatchBatchAccount                   = shared.NewItemType(Azure, Batch, BatchAccount)
	BatchBatchApplication               = shared.NewItemType(Azure, Batch, BatchApplication)
	BatchBatchApplicationPackage        = shared.NewItemType(Azure, Batch, BatchApplicationPackage)
	BatchBatchPool                      = shared.NewItemType(Azure, Batch, BatchPool)
	BatchBatchCertificate               = shared.NewItemType(Azure, Batch, BatchCertificate)
	BatchBatchPrivateEndpointConnection = shared.NewItemType(Azure, Batch, BatchPrivateEndpointConnection)
	BatchBatchPrivateLinkResource       = shared.NewItemType(Azure, Batch, BatchPrivateLinkResource)
	BatchBatchDetector                  = shared.NewItemType(Azure, Batch, BatchDetector)

	// ElasticSAN item types
	ElasticSanVolumeSnapshot = shared.NewItemType(Azure, ElasticSAN, VolumeSnapshot)
)
