// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config.proto

package sdp

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountConfig_BlastRadiusPreset int32

const (
	// Customise advanced limits.
	AccountConfig_CUSTOM AccountConfig_BlastRadiusPreset = 0
	// Runs a shallow scan for dependencies. Reduces time takes to calculate
	// blast radius, but might mean some dependencies are missed
	AccountConfig_QUICK AccountConfig_BlastRadiusPreset = 1
	// An optimised balance between time taken and discovery.
	AccountConfig_DETAILED AccountConfig_BlastRadiusPreset = 2
	// Discovers all possible dependencies, might take a long time and
	// discover items that are less likely to be relevant to a change.
	AccountConfig_FULL AccountConfig_BlastRadiusPreset = 3
)

// Enum value maps for AccountConfig_BlastRadiusPreset.
var (
	AccountConfig_BlastRadiusPreset_name = map[int32]string{
		0: "CUSTOM",
		1: "QUICK",
		2: "DETAILED",
		3: "FULL",
	}
	AccountConfig_BlastRadiusPreset_value = map[string]int32{
		"CUSTOM":   0,
		"QUICK":    1,
		"DETAILED": 2,
		"FULL":     3,
	}
)

func (x AccountConfig_BlastRadiusPreset) Enum() *AccountConfig_BlastRadiusPreset {
	p := new(AccountConfig_BlastRadiusPreset)
	*p = x
	return p
}

func (x AccountConfig_BlastRadiusPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountConfig_BlastRadiusPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (AccountConfig_BlastRadiusPreset) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x AccountConfig_BlastRadiusPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountConfig_BlastRadiusPreset.Descriptor instead.
func (AccountConfig_BlastRadiusPreset) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1, 0}
}

type GetHcpConfigResponse_Status int32

const (
	// The HCP Run Task configuration is active and can be used
	GetHcpConfigResponse_CONFIGURED GetHcpConfigResponse_Status = 0
	// The HCP Run Task configuration is not fully configured and needs to
	// be recreated, this is usually due to the API key being revoked or the
	// user not completing the authorisation process
	GetHcpConfigResponse_ERROR GetHcpConfigResponse_Status = 1
)

// Enum value maps for GetHcpConfigResponse_Status.
var (
	GetHcpConfigResponse_Status_name = map[int32]string{
		0: "CONFIGURED",
		1: "ERROR",
	}
	GetHcpConfigResponse_Status_value = map[string]int32{
		"CONFIGURED": 0,
		"ERROR":      1,
	}
)

func (x GetHcpConfigResponse_Status) Enum() *GetHcpConfigResponse_Status {
	p := new(GetHcpConfigResponse_Status)
	*p = x
	return p
}

func (x GetHcpConfigResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetHcpConfigResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (GetHcpConfigResponse_Status) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x GetHcpConfigResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetHcpConfigResponse_Status.Descriptor instead.
func (GetHcpConfigResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10, 0}
}

type RoutineChangesConfig_DurationUnit int32

const (
	// Days
	RoutineChangesConfig_DAYS RoutineChangesConfig_DurationUnit = 0
	// Weeks
	RoutineChangesConfig_WEEKS RoutineChangesConfig_DurationUnit = 1
	// Months
	RoutineChangesConfig_MONTHS RoutineChangesConfig_DurationUnit = 2
)

// Enum value maps for RoutineChangesConfig_DurationUnit.
var (
	RoutineChangesConfig_DurationUnit_name = map[int32]string{
		0: "DAYS",
		1: "WEEKS",
		2: "MONTHS",
	}
	RoutineChangesConfig_DurationUnit_value = map[string]int32{
		"DAYS":   0,
		"WEEKS":  1,
		"MONTHS": 2,
	}
)

func (x RoutineChangesConfig_DurationUnit) Enum() *RoutineChangesConfig_DurationUnit {
	p := new(RoutineChangesConfig_DurationUnit)
	*p = x
	return p
}

func (x RoutineChangesConfig_DurationUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutineChangesConfig_DurationUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[2].Descriptor()
}

func (RoutineChangesConfig_DurationUnit) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[2]
}

func (x RoutineChangesConfig_DurationUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutineChangesConfig_DurationUnit.Descriptor instead.
func (RoutineChangesConfig_DurationUnit) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{19, 0}
}

// The config that is used when calculating the blast radius for a change, this
// does not affect manually requested blast radii vie the "Explore" view or the
// API
type BlastRadiusConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of items that can be returned in a single blast radius
	// request. Once a request has hit this limit, all currently running
	// requests will be cancelled and the blast radius returned as-is
	MaxItems int32 `protobuf:"varint,1,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	// How deeply to link when calculating the blast radius for a change
	LinkDepth     int32 `protobuf:"varint,2,opt,name=linkDepth,proto3" json:"linkDepth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlastRadiusConfig) Reset() {
	*x = BlastRadiusConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlastRadiusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlastRadiusConfig) ProtoMessage() {}

func (x *BlastRadiusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlastRadiusConfig.ProtoReflect.Descriptor instead.
func (*BlastRadiusConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *BlastRadiusConfig) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *BlastRadiusConfig) GetLinkDepth() int32 {
	if x != nil {
		return x.LinkDepth
	}
	return 0
}

// This account config is stored in the `kv.Store` protobuf key-value store in
// the api-server database. This means that as long as we don't have any
// *breaking* changes to the protobuf, we shouldn't need to do a migration. If
// however we do need to change this message in a breaking way, we will need to
// do some kind of a migration (depending on the change)
type AccountConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The preset that we should use when calculating the blast radius for a
	// change. If this is set to "CUSTOM" then the `blastRadius` config should be
	// set
	BlastRadiusPreset AccountConfig_BlastRadiusPreset `protobuf:"varint,2,opt,name=blastRadiusPreset,proto3,enum=config.AccountConfig_BlastRadiusPreset" json:"blastRadiusPreset,omitempty"`
	// The blast radius config for this account, this is only required if the
	// preset is "CUSTOM"
	BlastRadius *BlastRadiusConfig `protobuf:"bytes,1,opt,name=blastRadius,proto3,oneof" json:"blastRadius,omitempty"`
	// If this is set to true, changes that weren't able to be mapped to real
	// infrastructure won't be considered for risk calculations. This usually
	// reduces the number low-quality and low-severity risks, and focuses more
	// on risks that we have additional context for. If you find that Overmind's
	// risks are "too obvious" then this might be a good setting to enable.
	SkipUnmappedChangesForRisks bool `protobuf:"varint,3,opt,name=skipUnmappedChangesForRisks,proto3" json:"skipUnmappedChangesForRisks,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AccountConfig) Reset() {
	*x = AccountConfig{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountConfig) ProtoMessage() {}

func (x *AccountConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountConfig.ProtoReflect.Descriptor instead.
func (*AccountConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *AccountConfig) GetBlastRadiusPreset() AccountConfig_BlastRadiusPreset {
	if x != nil {
		return x.BlastRadiusPreset
	}
	return AccountConfig_CUSTOM
}

func (x *AccountConfig) GetBlastRadius() *BlastRadiusConfig {
	if x != nil {
		return x.BlastRadius
	}
	return nil
}

func (x *AccountConfig) GetSkipUnmappedChangesForRisks() bool {
	if x != nil {
		return x.SkipUnmappedChangesForRisks
	}
	return false
}

type GetAccountConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountConfigRequest) Reset() {
	*x = GetAccountConfigRequest{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountConfigRequest) ProtoMessage() {}

func (x *GetAccountConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAccountConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

type GetAccountConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AccountConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountConfigResponse) Reset() {
	*x = GetAccountConfigResponse{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountConfigResponse) ProtoMessage() {}

func (x *GetAccountConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAccountConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountConfigResponse) GetConfig() *AccountConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Updates the account config for the user's account.
type UpdateAccountConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AccountConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountConfigRequest) Reset() {
	*x = UpdateAccountConfigRequest{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountConfigRequest) ProtoMessage() {}

func (x *UpdateAccountConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAccountConfigRequest) GetConfig() *AccountConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateAccountConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AccountConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountConfigResponse) Reset() {
	*x = UpdateAccountConfigResponse{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountConfigResponse) ProtoMessage() {}

func (x *UpdateAccountConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccountConfigResponse) GetConfig() *AccountConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateHcpConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL that the user should be redirected to after the whole process is
	// over. This should be a page in the frontend, probably the HCP Terraform
	// Integration page.
	FinalFrontendRedirect string `protobuf:"bytes,1,opt,name=finalFrontendRedirect,proto3" json:"finalFrontendRedirect,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateHcpConfigRequest) Reset() {
	*x = CreateHcpConfigRequest{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHcpConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHcpConfigRequest) ProtoMessage() {}

func (x *CreateHcpConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHcpConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateHcpConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *CreateHcpConfigRequest) GetFinalFrontendRedirect() string {
	if x != nil {
		return x.FinalFrontendRedirect
	}
	return ""
}

type CreateHcpConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The configuration of the HCP Run Task that was created
	Config *HcpConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The API Key response for the API key that backs this integration. This
	// API will have been created but not yet authorised, the user must still be
	// redirected to the authorizeURL to complete the process.
	ApiKey        *CreateAPIKeyResponse `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHcpConfigResponse) Reset() {
	*x = CreateHcpConfigResponse{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHcpConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHcpConfigResponse) ProtoMessage() {}

func (x *CreateHcpConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHcpConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateHcpConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *CreateHcpConfigResponse) GetConfig() *HcpConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateHcpConfigResponse) GetApiKey() *CreateAPIKeyResponse {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type HcpConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the Endpoint URL for the HCP Run Task configuration
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// the HMAC secret for the HCP Run Task configuration
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HcpConfig) Reset() {
	*x = HcpConfig{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HcpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HcpConfig) ProtoMessage() {}

func (x *HcpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HcpConfig.ProtoReflect.Descriptor instead.
func (*HcpConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *HcpConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HcpConfig) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type GetHcpConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHcpConfigRequest) Reset() {
	*x = GetHcpConfigRequest{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHcpConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHcpConfigRequest) ProtoMessage() {}

func (x *GetHcpConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHcpConfigRequest.ProtoReflect.Descriptor instead.
func (*GetHcpConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

type GetHcpConfigResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Config        *HcpConfig                  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Status        GetHcpConfigResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=config.GetHcpConfigResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHcpConfigResponse) Reset() {
	*x = GetHcpConfigResponse{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHcpConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHcpConfigResponse) ProtoMessage() {}

func (x *GetHcpConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHcpConfigResponse.ProtoReflect.Descriptor instead.
func (*GetHcpConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *GetHcpConfigResponse) GetConfig() *HcpConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetHcpConfigResponse) GetStatus() GetHcpConfigResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetHcpConfigResponse_CONFIGURED
}

type DeleteHcpConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHcpConfigRequest) Reset() {
	*x = DeleteHcpConfigRequest{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHcpConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHcpConfigRequest) ProtoMessage() {}

func (x *DeleteHcpConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHcpConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteHcpConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

type DeleteHcpConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHcpConfigResponse) Reset() {
	*x = DeleteHcpConfigResponse{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHcpConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHcpConfigResponse) ProtoMessage() {}

func (x *DeleteHcpConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHcpConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteHcpConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

// Account Signal config
type GetSignalConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignalConfigRequest) Reset() {
	*x = GetSignalConfigRequest{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalConfigRequest) ProtoMessage() {}

func (x *GetSignalConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSignalConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{13}
}

type GetSignalConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SignalConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignalConfigResponse) Reset() {
	*x = GetSignalConfigResponse{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalConfigResponse) ProtoMessage() {}

func (x *GetSignalConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalConfigResponse.ProtoReflect.Descriptor instead.
func (*GetSignalConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14}
}

func (x *GetSignalConfigResponse) GetConfig() *SignalConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Updates the signal config for the account.
type UpdateSignalConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SignalConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSignalConfigRequest) Reset() {
	*x = UpdateSignalConfigRequest{}
	mi := &file_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSignalConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSignalConfigRequest) ProtoMessage() {}

func (x *UpdateSignalConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSignalConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateSignalConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSignalConfigRequest) GetConfig() *SignalConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateSignalConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SignalConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSignalConfigResponse) Reset() {
	*x = UpdateSignalConfigResponse{}
	mi := &file_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSignalConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSignalConfigResponse) ProtoMessage() {}

func (x *UpdateSignalConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSignalConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateSignalConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateSignalConfigResponse) GetConfig() *SignalConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SignalConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config for aggregation parameters, such as alpha
	AggregationConfig *AggregationConfig `protobuf:"bytes,1,opt,name=aggregationConfig,proto3" json:"aggregationConfig,omitempty"`
	// Config for routine changes, such as events per day and duration
	RoutineChangesConfig *RoutineChangesConfig `protobuf:"bytes,2,opt,name=routineChangesConfig,proto3" json:"routineChangesConfig,omitempty"`
	// Config for Github app profile, such as primary branch name
	GithubOrganisationProfile *GithubOrganisationProfile `protobuf:"bytes,3,opt,name=githubOrganisationProfile,proto3,oneof" json:"githubOrganisationProfile,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SignalConfig) Reset() {
	*x = SignalConfig{}
	mi := &file_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalConfig) ProtoMessage() {}

func (x *SignalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalConfig.ProtoReflect.Descriptor instead.
func (*SignalConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{17}
}

func (x *SignalConfig) GetAggregationConfig() *AggregationConfig {
	if x != nil {
		return x.AggregationConfig
	}
	return nil
}

func (x *SignalConfig) GetRoutineChangesConfig() *RoutineChangesConfig {
	if x != nil {
		return x.RoutineChangesConfig
	}
	return nil
}

func (x *SignalConfig) GetGithubOrganisationProfile() *GithubOrganisationProfile {
	if x != nil {
		return x.GithubOrganisationProfile
	}
	return nil
}

type AggregationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alpha parameter for aggregation: controls the weighting of recent data versus older data
	// Must be positive (greater than 0) as it's the temperature parameter for exponential decay
	Alpha         float32 `protobuf:"fixed32,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationConfig) Reset() {
	*x = AggregationConfig{}
	mi := &file_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationConfig) ProtoMessage() {}

func (x *AggregationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationConfig.ProtoReflect.Descriptor instead.
func (*AggregationConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{18}
}

func (x *AggregationConfig) GetAlpha() float32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

type RoutineChangesConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user will see the format of "12 changes per day for 3 weeks" with the user able to change these values i.e.
	// Events per days, weeks, or months
	EventsPer     float32                           `protobuf:"fixed32,1,opt,name=eventsPer,proto3" json:"eventsPer,omitempty"`
	EventsPerUnit RoutineChangesConfig_DurationUnit `protobuf:"varint,2,opt,name=eventsPerUnit,proto3,enum=config.RoutineChangesConfig_DurationUnit" json:"eventsPerUnit,omitempty"`
	// Duration the number of days, weeks, or months over which routine changes are considered.
	Duration float32 `protobuf:"fixed32,3,opt,name=duration,proto3" json:"duration,omitempty"`
	// Specifies the unit of time for the duration field in routine changes.
	// The available units are days, weeks, and months.
	DurationUnit RoutineChangesConfig_DurationUnit `protobuf:"varint,4,opt,name=durationUnit,proto3,enum=config.RoutineChangesConfig_DurationUnit" json:"durationUnit,omitempty"`
	// Sensitivity parameter that controls the threshold for detecting routine changes.
	// A higher sensitivity value makes the detection more responsive to smaller changes,
	// while a lower value makes it less responsive.
	Sensitivity   float32 `protobuf:"fixed32,5,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutineChangesConfig) Reset() {
	*x = RoutineChangesConfig{}
	mi := &file_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutineChangesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineChangesConfig) ProtoMessage() {}

func (x *RoutineChangesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineChangesConfig.ProtoReflect.Descriptor instead.
func (*RoutineChangesConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{19}
}

func (x *RoutineChangesConfig) GetEventsPer() float32 {
	if x != nil {
		return x.EventsPer
	}
	return 0
}

func (x *RoutineChangesConfig) GetEventsPerUnit() RoutineChangesConfig_DurationUnit {
	if x != nil {
		return x.EventsPerUnit
	}
	return RoutineChangesConfig_DAYS
}

func (x *RoutineChangesConfig) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RoutineChangesConfig) GetDurationUnit() RoutineChangesConfig_DurationUnit {
	if x != nil {
		return x.DurationUnit
	}
	return RoutineChangesConfig_DAYS
}

func (x *RoutineChangesConfig) GetSensitivity() float32 {
	if x != nil {
		return x.Sensitivity
	}
	return 0
}

// no parameters required, we will look up the installation ID from the account ID
type GetGithubAppInformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGithubAppInformationRequest) Reset() {
	*x = GetGithubAppInformationRequest{}
	mi := &file_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubAppInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubAppInformationRequest) ProtoMessage() {}

func (x *GetGithubAppInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubAppInformationRequest.ProtoReflect.Descriptor instead.
func (*GetGithubAppInformationRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{20}
}

// it will be used to display information to the github integrations page, it is not used for signal processing
type GithubAppInformation struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	InstallationID          int64                  `protobuf:"varint,1,opt,name=installationID,proto3" json:"installationID,omitempty"`
	InstalledBy             string                 `protobuf:"bytes,2,opt,name=installedBy,proto3" json:"installedBy,omitempty"`
	InstalledAt             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=installedAt,proto3" json:"installedAt,omitempty"`
	OrganisationName        string                 `protobuf:"bytes,4,opt,name=organisationName,proto3" json:"organisationName,omitempty"`
	ActiveRepositoryCount   int64                  `protobuf:"varint,5,opt,name=activeRepositoryCount,proto3" json:"activeRepositoryCount,omitempty"`
	ContributorCount        int64                  `protobuf:"varint,6,opt,name=contributorCount,proto3" json:"contributorCount,omitempty"`
	BotAutomationPercentage int64                  `protobuf:"varint,7,opt,name=botAutomationPercentage,proto3" json:"botAutomationPercentage,omitempty"`
	AverageMergeTime        string                 `protobuf:"bytes,8,opt,name=averageMergeTime,proto3" json:"averageMergeTime,omitempty"`
	AverageCommitFrequency  string                 `protobuf:"bytes,9,opt,name=averageCommitFrequency,proto3" json:"averageCommitFrequency,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GithubAppInformation) Reset() {
	*x = GithubAppInformation{}
	mi := &file_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubAppInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubAppInformation) ProtoMessage() {}

func (x *GithubAppInformation) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubAppInformation.ProtoReflect.Descriptor instead.
func (*GithubAppInformation) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{21}
}

func (x *GithubAppInformation) GetInstallationID() int64 {
	if x != nil {
		return x.InstallationID
	}
	return 0
}

func (x *GithubAppInformation) GetInstalledBy() string {
	if x != nil {
		return x.InstalledBy
	}
	return ""
}

func (x *GithubAppInformation) GetInstalledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InstalledAt
	}
	return nil
}

func (x *GithubAppInformation) GetOrganisationName() string {
	if x != nil {
		return x.OrganisationName
	}
	return ""
}

func (x *GithubAppInformation) GetActiveRepositoryCount() int64 {
	if x != nil {
		return x.ActiveRepositoryCount
	}
	return 0
}

func (x *GithubAppInformation) GetContributorCount() int64 {
	if x != nil {
		return x.ContributorCount
	}
	return 0
}

func (x *GithubAppInformation) GetBotAutomationPercentage() int64 {
	if x != nil {
		return x.BotAutomationPercentage
	}
	return 0
}

func (x *GithubAppInformation) GetAverageMergeTime() string {
	if x != nil {
		return x.AverageMergeTime
	}
	return ""
}

func (x *GithubAppInformation) GetAverageCommitFrequency() string {
	if x != nil {
		return x.AverageCommitFrequency
	}
	return ""
}

// this is all the information required to display the github app information
type GetGithubAppInformationResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GithubAppInformation *GithubAppInformation  `protobuf:"bytes,1,opt,name=githubAppInformation,proto3" json:"githubAppInformation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetGithubAppInformationResponse) Reset() {
	*x = GetGithubAppInformationResponse{}
	mi := &file_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubAppInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubAppInformationResponse) ProtoMessage() {}

func (x *GetGithubAppInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubAppInformationResponse.ProtoReflect.Descriptor instead.
func (*GetGithubAppInformationResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{22}
}

func (x *GetGithubAppInformationResponse) GetGithubAppInformation() *GithubAppInformation {
	if x != nil {
		return x.GithubAppInformation
	}
	return nil
}

// no parameters required, we will look up the installation ID from the account ID
type RegenerateGithubAppProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateGithubAppProfileRequest) Reset() {
	*x = RegenerateGithubAppProfileRequest{}
	mi := &file_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateGithubAppProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateGithubAppProfileRequest) ProtoMessage() {}

func (x *RegenerateGithubAppProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateGithubAppProfileRequest.ProtoReflect.Descriptor instead.
func (*RegenerateGithubAppProfileRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{23}
}

// information stored in the database, used by signal processing in change analysis
type GithubOrganisationProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PrimaryBranchName string                 `protobuf:"bytes,1,opt,name=primaryBranchName,proto3" json:"primaryBranchName,omitempty"`
	// signal scores that will be given for each hour of the day, 0-23, from -5.0 to 5.0
	HourlyScores  []float64 `protobuf:"fixed64,2,rep,packed,name=hourlyScores,proto3" json:"hourlyScores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubOrganisationProfile) Reset() {
	*x = GithubOrganisationProfile{}
	mi := &file_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubOrganisationProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubOrganisationProfile) ProtoMessage() {}

func (x *GithubOrganisationProfile) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubOrganisationProfile.ProtoReflect.Descriptor instead.
func (*GithubOrganisationProfile) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{24}
}

func (x *GithubOrganisationProfile) GetPrimaryBranchName() string {
	if x != nil {
		return x.PrimaryBranchName
	}
	return ""
}

func (x *GithubOrganisationProfile) GetHourlyScores() []float64 {
	if x != nil {
		return x.HourlyScores
	}
	return nil
}

type RegenerateGithubAppProfileResponse struct {
	state                     protoimpl.MessageState     `protogen:"open.v1"`
	GithubOrganisationProfile *GithubOrganisationProfile `protobuf:"bytes,1,opt,name=githubOrganisationProfile,proto3" json:"githubOrganisationProfile,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RegenerateGithubAppProfileResponse) Reset() {
	*x = RegenerateGithubAppProfileResponse{}
	mi := &file_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateGithubAppProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateGithubAppProfileResponse) ProtoMessage() {}

func (x *RegenerateGithubAppProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateGithubAppProfileResponse.ProtoReflect.Descriptor instead.
func (*RegenerateGithubAppProfileResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{25}
}

func (x *RegenerateGithubAppProfileResponse) GetGithubOrganisationProfile() *GithubOrganisationProfile {
	if x != nil {
		return x.GithubOrganisationProfile
	}
	return nil
}

// no parameters required, we will look up the installation ID from the account ID
type DeleteGithubAppProfileAndGithubInstallationIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGithubAppProfileAndGithubInstallationIDRequest) Reset() {
	*x = DeleteGithubAppProfileAndGithubInstallationIDRequest{}
	mi := &file_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGithubAppProfileAndGithubInstallationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGithubAppProfileAndGithubInstallationIDRequest) ProtoMessage() {}

func (x *DeleteGithubAppProfileAndGithubInstallationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGithubAppProfileAndGithubInstallationIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteGithubAppProfileAndGithubInstallationIDRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{26}
}

// status codes to indicate if the deletion was successful
type DeleteGithubAppProfileAndGithubInstallationIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGithubAppProfileAndGithubInstallationIDResponse) Reset() {
	*x = DeleteGithubAppProfileAndGithubInstallationIDResponse{}
	mi := &file_config_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGithubAppProfileAndGithubInstallationIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGithubAppProfileAndGithubInstallationIDResponse) ProtoMessage() {}

func (x *DeleteGithubAppProfileAndGithubInstallationIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGithubAppProfileAndGithubInstallationIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteGithubAppProfileAndGithubInstallationIDResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{27}
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x06config\x1a\rapikeys.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\x11BlastRadiusConfig\x12\x1a\n" +
	"\bmaxItems\x18\x01 \x01(\x05R\bmaxItems\x12\x1c\n" +
	"\tlinkDepth\x18\x02 \x01(\x05R\tlinkDepth\"\xbe\x02\n" +
	"\rAccountConfig\x12U\n" +
	"\x11blastRadiusPreset\x18\x02 \x01(\x0e2'.config.AccountConfig.BlastRadiusPresetR\x11blastRadiusPreset\x12@\n" +
	"\vblastRadius\x18\x01 \x01(\v2\x19.config.BlastRadiusConfigH\x00R\vblastRadius\x88\x01\x01\x12@\n" +
	"\x1bskipUnmappedChangesForRisks\x18\x03 \x01(\bR\x1bskipUnmappedChangesForRisks\"B\n" +
	"\x11BlastRadiusPreset\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x00\x12\t\n" +
	"\x05QUICK\x10\x01\x12\f\n" +
	"\bDETAILED\x10\x02\x12\b\n" +
	"\x04FULL\x10\x03B\x0e\n" +
	"\f_blastRadius\"\x19\n" +
	"\x17GetAccountConfigRequest\"I\n" +
	"\x18GetAccountConfigResponse\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.config.AccountConfigR\x06config\"K\n" +
	"\x1aUpdateAccountConfigRequest\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.config.AccountConfigR\x06config\"L\n" +
	"\x1bUpdateAccountConfigResponse\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.config.AccountConfigR\x06config\"N\n" +
	"\x16CreateHcpConfigRequest\x124\n" +
	"\x15finalFrontendRedirect\x18\x01 \x01(\tR\x15finalFrontendRedirect\"{\n" +
	"\x17CreateHcpConfigResponse\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.config.HcpConfigR\x06config\x125\n" +
	"\x06apiKey\x18\x02 \x01(\v2\x1d.apikeys.CreateAPIKeyResponseR\x06apiKey\"?\n" +
	"\tHcpConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\x15\n" +
	"\x13GetHcpConfigRequest\"\xa3\x01\n" +
	"\x14GetHcpConfigResponse\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.config.HcpConfigR\x06config\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.config.GetHcpConfigResponse.StatusR\x06status\"#\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"CONFIGURED\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\"\x18\n" +
	"\x16DeleteHcpConfigRequest\"\x19\n" +
	"\x17DeleteHcpConfigResponse\"\x18\n" +
	"\x16GetSignalConfigRequest\"G\n" +
	"\x17GetSignalConfigResponse\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.SignalConfigR\x06config\"I\n" +
	"\x19UpdateSignalConfigRequest\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.SignalConfigR\x06config\"J\n" +
	"\x1aUpdateSignalConfigResponse\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.SignalConfigR\x06config\"\xad\x02\n" +
	"\fSignalConfig\x12G\n" +
	"\x11aggregationConfig\x18\x01 \x01(\v2\x19.config.AggregationConfigR\x11aggregationConfig\x12P\n" +
	"\x14routineChangesConfig\x18\x02 \x01(\v2\x1c.config.RoutineChangesConfigR\x14routineChangesConfig\x12d\n" +
	"\x19githubOrganisationProfile\x18\x03 \x01(\v2!.config.GithubOrganisationProfileH\x00R\x19githubOrganisationProfile\x88\x01\x01B\x1c\n" +
	"\x1a_githubOrganisationProfile\"5\n" +
	"\x11AggregationConfig\x12 \n" +
	"\x05alpha\x18\x01 \x01(\x02B\n" +
	"\xbaH\a\n" +
	"\x05%\x00\x00\x00\x00R\x05alpha\"\xc3\x02\n" +
	"\x14RoutineChangesConfig\x12\x1c\n" +
	"\teventsPer\x18\x01 \x01(\x02R\teventsPer\x12O\n" +
	"\reventsPerUnit\x18\x02 \x01(\x0e2).config.RoutineChangesConfig.DurationUnitR\reventsPerUnit\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x02R\bduration\x12M\n" +
	"\fdurationUnit\x18\x04 \x01(\x0e2).config.RoutineChangesConfig.DurationUnitR\fdurationUnit\x12 \n" +
	"\vsensitivity\x18\x05 \x01(\x02R\vsensitivity\"/\n" +
	"\fDurationUnit\x12\b\n" +
	"\x04DAYS\x10\x00\x12\t\n" +
	"\x05WEEKS\x10\x01\x12\n" +
	"\n" +
	"\x06MONTHS\x10\x02\" \n" +
	"\x1eGetGithubAppInformationRequest\"\xca\x03\n" +
	"\x14GithubAppInformation\x12&\n" +
	"\x0einstallationID\x18\x01 \x01(\x03R\x0einstallationID\x12 \n" +
	"\vinstalledBy\x18\x02 \x01(\tR\vinstalledBy\x12<\n" +
	"\vinstalledAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vinstalledAt\x12*\n" +
	"\x10organisationName\x18\x04 \x01(\tR\x10organisationName\x124\n" +
	"\x15activeRepositoryCount\x18\x05 \x01(\x03R\x15activeRepositoryCount\x12*\n" +
	"\x10contributorCount\x18\x06 \x01(\x03R\x10contributorCount\x128\n" +
	"\x17botAutomationPercentage\x18\a \x01(\x03R\x17botAutomationPercentage\x12*\n" +
	"\x10averageMergeTime\x18\b \x01(\tR\x10averageMergeTime\x126\n" +
	"\x16averageCommitFrequency\x18\t \x01(\tR\x16averageCommitFrequency\"s\n" +
	"\x1fGetGithubAppInformationResponse\x12P\n" +
	"\x14githubAppInformation\x18\x01 \x01(\v2\x1c.config.GithubAppInformationR\x14githubAppInformation\"#\n" +
	"!RegenerateGithubAppProfileRequest\"\x8f\x01\n" +
	"\x19GithubOrganisationProfile\x12,\n" +
	"\x11primaryBranchName\x18\x01 \x01(\tR\x11primaryBranchName\x12D\n" +
	"\fhourlyScores\x18\x02 \x03(\x01B \xbaH\x1d\x92\x01\x1a\b\x18\x10\x18\"\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\x14@)\x00\x00\x00\x00\x00\x00\x14\xc0R\fhourlyScores\"\x85\x01\n" +
	"\"RegenerateGithubAppProfileResponse\x12_\n" +
	"\x19githubOrganisationProfile\x18\x01 \x01(\v2!.config.GithubOrganisationProfileR\x19githubOrganisationProfile\"6\n" +
	"4DeleteGithubAppProfileAndGithubInstallationIDRequest\"7\n" +
	"5DeleteGithubAppProfileAndGithubInstallationIDResponse2\x81\b\n" +
	"\x14ConfigurationService\x12U\n" +
	"\x10GetAccountConfig\x12\x1f.config.GetAccountConfigRequest\x1a .config.GetAccountConfigResponse\x12^\n" +
	"\x13UpdateAccountConfig\x12\".config.UpdateAccountConfigRequest\x1a#.config.UpdateAccountConfigResponse\x12R\n" +
	"\x0fCreateHcpConfig\x12\x1e.config.CreateHcpConfigRequest\x1a\x1f.config.CreateHcpConfigResponse\x12I\n" +
	"\fGetHcpConfig\x12\x1b.config.GetHcpConfigRequest\x1a\x1c.config.GetHcpConfigResponse\x12R\n" +
	"\x0fDeleteHcpConfig\x12\x1e.config.DeleteHcpConfigRequest\x1a\x1f.config.DeleteHcpConfigResponse\x12R\n" +
	"\x0fGetSignalConfig\x12\x1e.config.GetSignalConfigRequest\x1a\x1f.config.GetSignalConfigResponse\x12[\n" +
	"\x12UpdateSignalConfig\x12!.config.UpdateSignalConfigRequest\x1a\".config.UpdateSignalConfigResponse\x12j\n" +
	"\x17GetGithubAppInformation\x12&.config.GetGithubAppInformationRequest\x1a'.config.GetGithubAppInformationResponse\x12s\n" +
	"\x1aRegenerateGithubAppProfile\x12).config.RegenerateGithubAppProfileRequest\x1a*.config.RegenerateGithubAppProfileResponse\x12\xac\x01\n" +
	"-DeleteGithubAppProfileAndGithubInstallationID\x12<.config.DeleteGithubAppProfileAndGithubInstallationIDRequest\x1a=.config.DeleteGithubAppProfileAndGithubInstallationIDResponseB.Z,github.com/overmindtech/workspace/sdp-go;sdpb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_config_proto_goTypes = []any{
	(AccountConfig_BlastRadiusPreset)(0),                          // 0: config.AccountConfig.BlastRadiusPreset
	(GetHcpConfigResponse_Status)(0),                              // 1: config.GetHcpConfigResponse.Status
	(RoutineChangesConfig_DurationUnit)(0),                        // 2: config.RoutineChangesConfig.DurationUnit
	(*BlastRadiusConfig)(nil),                                     // 3: config.BlastRadiusConfig
	(*AccountConfig)(nil),                                         // 4: config.AccountConfig
	(*GetAccountConfigRequest)(nil),                               // 5: config.GetAccountConfigRequest
	(*GetAccountConfigResponse)(nil),                              // 6: config.GetAccountConfigResponse
	(*UpdateAccountConfigRequest)(nil),                            // 7: config.UpdateAccountConfigRequest
	(*UpdateAccountConfigResponse)(nil),                           // 8: config.UpdateAccountConfigResponse
	(*CreateHcpConfigRequest)(nil),                                // 9: config.CreateHcpConfigRequest
	(*CreateHcpConfigResponse)(nil),                               // 10: config.CreateHcpConfigResponse
	(*HcpConfig)(nil),                                             // 11: config.HcpConfig
	(*GetHcpConfigRequest)(nil),                                   // 12: config.GetHcpConfigRequest
	(*GetHcpConfigResponse)(nil),                                  // 13: config.GetHcpConfigResponse
	(*DeleteHcpConfigRequest)(nil),                                // 14: config.DeleteHcpConfigRequest
	(*DeleteHcpConfigResponse)(nil),                               // 15: config.DeleteHcpConfigResponse
	(*GetSignalConfigRequest)(nil),                                // 16: config.GetSignalConfigRequest
	(*GetSignalConfigResponse)(nil),                               // 17: config.GetSignalConfigResponse
	(*UpdateSignalConfigRequest)(nil),                             // 18: config.UpdateSignalConfigRequest
	(*UpdateSignalConfigResponse)(nil),                            // 19: config.UpdateSignalConfigResponse
	(*SignalConfig)(nil),                                          // 20: config.SignalConfig
	(*AggregationConfig)(nil),                                     // 21: config.AggregationConfig
	(*RoutineChangesConfig)(nil),                                  // 22: config.RoutineChangesConfig
	(*GetGithubAppInformationRequest)(nil),                        // 23: config.GetGithubAppInformationRequest
	(*GithubAppInformation)(nil),                                  // 24: config.GithubAppInformation
	(*GetGithubAppInformationResponse)(nil),                       // 25: config.GetGithubAppInformationResponse
	(*RegenerateGithubAppProfileRequest)(nil),                     // 26: config.RegenerateGithubAppProfileRequest
	(*GithubOrganisationProfile)(nil),                             // 27: config.GithubOrganisationProfile
	(*RegenerateGithubAppProfileResponse)(nil),                    // 28: config.RegenerateGithubAppProfileResponse
	(*DeleteGithubAppProfileAndGithubInstallationIDRequest)(nil),  // 29: config.DeleteGithubAppProfileAndGithubInstallationIDRequest
	(*DeleteGithubAppProfileAndGithubInstallationIDResponse)(nil), // 30: config.DeleteGithubAppProfileAndGithubInstallationIDResponse
	(*CreateAPIKeyResponse)(nil),                                  // 31: apikeys.CreateAPIKeyResponse
	(*timestamppb.Timestamp)(nil),                                 // 32: google.protobuf.Timestamp
}
var file_config_proto_depIdxs = []int32{
	0,  // 0: config.AccountConfig.blastRadiusPreset:type_name -> config.AccountConfig.BlastRadiusPreset
	3,  // 1: config.AccountConfig.blastRadius:type_name -> config.BlastRadiusConfig
	4,  // 2: config.GetAccountConfigResponse.config:type_name -> config.AccountConfig
	4,  // 3: config.UpdateAccountConfigRequest.config:type_name -> config.AccountConfig
	4,  // 4: config.UpdateAccountConfigResponse.config:type_name -> config.AccountConfig
	11, // 5: config.CreateHcpConfigResponse.config:type_name -> config.HcpConfig
	31, // 6: config.CreateHcpConfigResponse.apiKey:type_name -> apikeys.CreateAPIKeyResponse
	11, // 7: config.GetHcpConfigResponse.config:type_name -> config.HcpConfig
	1,  // 8: config.GetHcpConfigResponse.status:type_name -> config.GetHcpConfigResponse.Status
	20, // 9: config.GetSignalConfigResponse.config:type_name -> config.SignalConfig
	20, // 10: config.UpdateSignalConfigRequest.config:type_name -> config.SignalConfig
	20, // 11: config.UpdateSignalConfigResponse.config:type_name -> config.SignalConfig
	21, // 12: config.SignalConfig.aggregationConfig:type_name -> config.AggregationConfig
	22, // 13: config.SignalConfig.routineChangesConfig:type_name -> config.RoutineChangesConfig
	27, // 14: config.SignalConfig.githubOrganisationProfile:type_name -> config.GithubOrganisationProfile
	2,  // 15: config.RoutineChangesConfig.eventsPerUnit:type_name -> config.RoutineChangesConfig.DurationUnit
	2,  // 16: config.RoutineChangesConfig.durationUnit:type_name -> config.RoutineChangesConfig.DurationUnit
	32, // 17: config.GithubAppInformation.installedAt:type_name -> google.protobuf.Timestamp
	24, // 18: config.GetGithubAppInformationResponse.githubAppInformation:type_name -> config.GithubAppInformation
	27, // 19: config.RegenerateGithubAppProfileResponse.githubOrganisationProfile:type_name -> config.GithubOrganisationProfile
	5,  // 20: config.ConfigurationService.GetAccountConfig:input_type -> config.GetAccountConfigRequest
	7,  // 21: config.ConfigurationService.UpdateAccountConfig:input_type -> config.UpdateAccountConfigRequest
	9,  // 22: config.ConfigurationService.CreateHcpConfig:input_type -> config.CreateHcpConfigRequest
	12, // 23: config.ConfigurationService.GetHcpConfig:input_type -> config.GetHcpConfigRequest
	14, // 24: config.ConfigurationService.DeleteHcpConfig:input_type -> config.DeleteHcpConfigRequest
	16, // 25: config.ConfigurationService.GetSignalConfig:input_type -> config.GetSignalConfigRequest
	18, // 26: config.ConfigurationService.UpdateSignalConfig:input_type -> config.UpdateSignalConfigRequest
	23, // 27: config.ConfigurationService.GetGithubAppInformation:input_type -> config.GetGithubAppInformationRequest
	26, // 28: config.ConfigurationService.RegenerateGithubAppProfile:input_type -> config.RegenerateGithubAppProfileRequest
	29, // 29: config.ConfigurationService.DeleteGithubAppProfileAndGithubInstallationID:input_type -> config.DeleteGithubAppProfileAndGithubInstallationIDRequest
	6,  // 30: config.ConfigurationService.GetAccountConfig:output_type -> config.GetAccountConfigResponse
	8,  // 31: config.ConfigurationService.UpdateAccountConfig:output_type -> config.UpdateAccountConfigResponse
	10, // 32: config.ConfigurationService.CreateHcpConfig:output_type -> config.CreateHcpConfigResponse
	13, // 33: config.ConfigurationService.GetHcpConfig:output_type -> config.GetHcpConfigResponse
	15, // 34: config.ConfigurationService.DeleteHcpConfig:output_type -> config.DeleteHcpConfigResponse
	17, // 35: config.ConfigurationService.GetSignalConfig:output_type -> config.GetSignalConfigResponse
	19, // 36: config.ConfigurationService.UpdateSignalConfig:output_type -> config.UpdateSignalConfigResponse
	25, // 37: config.ConfigurationService.GetGithubAppInformation:output_type -> config.GetGithubAppInformationResponse
	28, // 38: config.ConfigurationService.RegenerateGithubAppProfile:output_type -> config.RegenerateGithubAppProfileResponse
	30, // 39: config.ConfigurationService.DeleteGithubAppProfileAndGithubInstallationID:output_type -> config.DeleteGithubAppProfileAndGithubInstallationIDResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_apikeys_proto_init()
	file_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_config_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
