// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: signal.proto

package sdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalLevel_Level int32

const (
	SignalLevel_UNSPECIFIED SignalLevel_Level = 0 // This is the default value, it should not be used
	// A change-level signal, top level summary of all Items below it by category, and aggregated by value. EG
	//
	//	{
	//		Metadata: &sdp.SignalMetadata{
	//			UUID: changeUUID[:],
	//		},
	//		Properties: &sdp.SignalProperties{
	//			Name:        "Routine",
	//			Description: "Recent infrastructure changes span multiple attributes, with modification frequencies ranging from first-time updates to daily deployments.",
	//			Category:    "Routine",
	//			Value:       0.0,
	//		},
	//	},
	//
	//	{
	//		Metadata: &sdp.SignalMetadata{
	//			UUID: changeUUID[:],
	//		},
	//		Properties: &sdp.SignalProperties{
	//			Name:        "Policies",
	//			Description: "Policy evaluations reveal a mix of compliant configurations, partially implemented controls such as unvalidated CloudTrail logging, and high-risk exposures like unrestricted SSH access.",
	//			Category:    "Policies",
	//			Value:       -3.0,
	//		},
	//	},
	SignalLevel_CHANGE SignalLevel_Level = 1
	// An item-level signal, GUN/Resource/Item summary of all details (attributes/modifications) of an item by category and aggregated by value. EG
	//
	//	{
	//		Metadata: &sdp.SignalMetadata{
	//			UUID: changeUUID[:],
	//		},
	//		Properties: &sdp.SignalProperties{
	//			Name:        "gp2",
	//			Description: "High Risk",
	//			Category:    "Change type",
	//			Value:       -1.0,
	//		},
	//	},
	//
	//	{
	//		Metadata: &sdp.SignalMetadata{
	//			UUID: changeUUID[:],
	//		},
	//		Properties: &sdp.SignalProperties{
	//			Name:        "gp2",
	//			Description: "Consistent activity of 1.5 events per day has been observed over the last 2 days.",
	//			Category:    "Routine",
	//			Value:       0.0,
	//		},
	//	},
	SignalLevel_ITEM SignalLevel_Level = 2
	// A detail-level signal, description and value of an attribute/modification. EG
	//
	//	{
	//		Metadata: &sdp.SignalMetadata{
	//			UUID: changeUUID[:],
	//		},
	//		Properties: &sdp.SignalProperties{
	//			Name:        "size",
	//			Description: "5 changes per week in the last 3 weeks",
	//			Category:    "Routine",
	//			Value:       0.0,
	//		},
	//	},
	//
	//	{
	//		Metadata: &sdp.SignalMetadata{
	//			UUID: changeUUID[:],
	//		},
	//		Properties: &sdp.SignalProperties{
	//			Name:        "security_group",
	//			Description: "5 changes per day in the last 5 weeks",
	//			Category:    "Routine",
	//			Value:       5.0,
	//		},
	//	},
	SignalLevel_DETAIL SignalLevel_Level = 3
)

// Enum value maps for SignalLevel_Level.
var (
	SignalLevel_Level_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CHANGE",
		2: "ITEM",
		3: "DETAIL",
	}
	SignalLevel_Level_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CHANGE":      1,
		"ITEM":        2,
		"DETAIL":      3,
	}
)

func (x SignalLevel_Level) Enum() *SignalLevel_Level {
	p := new(SignalLevel_Level)
	*p = x
	return p
}

func (x SignalLevel_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalLevel_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_signal_proto_enumTypes[0].Descriptor()
}

func (SignalLevel_Level) Type() protoreflect.EnumType {
	return &file_signal_proto_enumTypes[0]
}

func (x SignalLevel_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalLevel_Level.Descriptor instead.
func (SignalLevel_Level) EnumDescriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{13, 0}
}

type AddSignalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user facing properties of the signal
	Properties *SignalProperties `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	// UUID of the change this signal is associated with
	ChangeExternalId []byte `protobuf:"bytes,2,opt,name=change_external_id,json=changeExternalId,proto3" json:"change_external_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddSignalRequest) Reset() {
	*x = AddSignalRequest{}
	mi := &file_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSignalRequest) ProtoMessage() {}

func (x *AddSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSignalRequest.ProtoReflect.Descriptor instead.
func (*AddSignalRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{0}
}

func (x *AddSignalRequest) GetProperties() *SignalProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *AddSignalRequest) GetChangeExternalId() []byte {
	if x != nil {
		return x.ChangeExternalId
	}
	return nil
}

type AddSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *Signal                `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"` // The signal that was added
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSignalResponse) Reset() {
	*x = AddSignalResponse{}
	mi := &file_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSignalResponse) ProtoMessage() {}

func (x *AddSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSignalResponse.ProtoReflect.Descriptor instead.
func (*AddSignalResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{1}
}

func (x *AddSignalResponse) GetSignal() *Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type GetSignalsByChangeExternalIDRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChangeExternalId []byte                 `protobuf:"bytes,1,opt,name=change_external_id,json=changeExternalId,proto3" json:"change_external_id,omitempty"` // UUID of the change
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSignalsByChangeExternalIDRequest) Reset() {
	*x = GetSignalsByChangeExternalIDRequest{}
	mi := &file_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalsByChangeExternalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalsByChangeExternalIDRequest) ProtoMessage() {}

func (x *GetSignalsByChangeExternalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalsByChangeExternalIDRequest.ProtoReflect.Descriptor instead.
func (*GetSignalsByChangeExternalIDRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{2}
}

func (x *GetSignalsByChangeExternalIDRequest) GetChangeExternalId() []byte {
	if x != nil {
		return x.ChangeExternalId
	}
	return nil
}

type GetSignalsByChangeExternalIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"` // List of all signals associated with the change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignalsByChangeExternalIDResponse) Reset() {
	*x = GetSignalsByChangeExternalIDResponse{}
	mi := &file_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalsByChangeExternalIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalsByChangeExternalIDResponse) ProtoMessage() {}

func (x *GetSignalsByChangeExternalIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalsByChangeExternalIDResponse.ProtoReflect.Descriptor instead.
func (*GetSignalsByChangeExternalIDResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{3}
}

func (x *GetSignalsByChangeExternalIDResponse) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

type GetChangeOverviewSignalsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChangeExternalId []byte                 `protobuf:"bytes,1,opt,name=change_external_id,json=changeExternalId,proto3" json:"change_external_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetChangeOverviewSignalsRequest) Reset() {
	*x = GetChangeOverviewSignalsRequest{}
	mi := &file_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangeOverviewSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangeOverviewSignalsRequest) ProtoMessage() {}

func (x *GetChangeOverviewSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangeOverviewSignalsRequest.ProtoReflect.Descriptor instead.
func (*GetChangeOverviewSignalsRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{4}
}

func (x *GetChangeOverviewSignalsRequest) GetChangeExternalId() []byte {
	if x != nil {
		return x.ChangeExternalId
	}
	return nil
}

type GetChangeOverviewSignalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangeOverviewSignalsResponse) Reset() {
	*x = GetChangeOverviewSignalsResponse{}
	mi := &file_signal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangeOverviewSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangeOverviewSignalsResponse) ProtoMessage() {}

func (x *GetChangeOverviewSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangeOverviewSignalsResponse.ProtoReflect.Descriptor instead.
func (*GetChangeOverviewSignalsResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{5}
}

func (x *GetChangeOverviewSignalsResponse) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

type GetItemSignalsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChangeExternalId []byte                 `protobuf:"bytes,2,opt,name=change_external_id,json=changeExternalId,proto3" json:"change_external_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetItemSignalsRequest) Reset() {
	*x = GetItemSignalsRequest{}
	mi := &file_signal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemSignalsRequest) ProtoMessage() {}

func (x *GetItemSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemSignalsRequest.ProtoReflect.Descriptor instead.
func (*GetItemSignalsRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemSignalsRequest) GetChangeExternalId() []byte {
	if x != nil {
		return x.ChangeExternalId
	}
	return nil
}

type GetItemSignalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemSignalsResponse) Reset() {
	*x = GetItemSignalsResponse{}
	mi := &file_signal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemSignalsResponse) ProtoMessage() {}

func (x *GetItemSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemSignalsResponse.ProtoReflect.Descriptor instead.
func (*GetItemSignalsResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{7}
}

func (x *GetItemSignalsResponse) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

type GetItemSignalDetailsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Item             *Reference             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	ChangeExternalId []byte                 `protobuf:"bytes,2,opt,name=change_external_id,json=changeExternalId,proto3" json:"change_external_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetItemSignalDetailsRequest) Reset() {
	*x = GetItemSignalDetailsRequest{}
	mi := &file_signal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemSignalDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemSignalDetailsRequest) ProtoMessage() {}

func (x *GetItemSignalDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemSignalDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetItemSignalDetailsRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemSignalDetailsRequest) GetItem() *Reference {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetItemSignalDetailsRequest) GetChangeExternalId() []byte {
	if x != nil {
		return x.ChangeExternalId
	}
	return nil
}

type GetItemSignalDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemSignalDetailsResponse) Reset() {
	*x = GetItemSignalDetailsResponse{}
	mi := &file_signal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemSignalDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemSignalDetailsResponse) ProtoMessage() {}

func (x *GetItemSignalDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemSignalDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetItemSignalDetailsResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{9}
}

func (x *GetItemSignalDetailsResponse) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

type SignalMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// machine-generated metadata of this signal
	// unique id to identify this change
	UUID []byte `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Aggregation ID is used to identify the aggregation in cache
	AggregationID string `protobuf:"bytes,2,opt,name=aggregationID,proto3" json:"aggregationID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMetadata) Reset() {
	*x = SignalMetadata{}
	mi := &file_signal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMetadata) ProtoMessage() {}

func (x *SignalMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMetadata.ProtoReflect.Descriptor instead.
func (*SignalMetadata) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{10}
}

func (x *SignalMetadata) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *SignalMetadata) GetAggregationID() string {
	if x != nil {
		return x.AggregationID
	}
	return ""
}

type SignalProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user-supplied properties of this signal
	// A short name for the signal
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This is float64 value, representing the signal's value. -5 to +5. +5 is very high / strong, 0 is neutral, -5 is very low / weak.
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	// A one sentence description of the signal, it could be activity in routineness, or another
	// descriptive text
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// A category for the signal, e.g. "routineness", "anomaly", etc. How it will be grouped in the UI.
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// A reference to the item/resource that this signal is related to (can be nil)
	Item          *Reference `protobuf:"bytes,5,opt,name=item,proto3,oneof" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalProperties) Reset() {
	*x = SignalProperties{}
	mi := &file_signal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProperties) ProtoMessage() {}

func (x *SignalProperties) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProperties.ProtoReflect.Descriptor instead.
func (*SignalProperties) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{11}
}

func (x *SignalProperties) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignalProperties) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SignalProperties) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SignalProperties) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SignalProperties) GetItem() *Reference {
	if x != nil {
		return x.Item
	}
	return nil
}

// we mimic the layout of the changes object here, because there are 2 parts
// to a signal: the machine-generated metadata and the user-supplied properties.
type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// machine-generated metadata of this signal
	Metadata *SignalMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// user-supplied properties of this signal
	Properties    *SignalProperties `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_signal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{12}
}

func (x *Signal) GetMetadata() *SignalMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Signal) GetProperties() *SignalProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type SignalLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         SignalLevel_Level      `protobuf:"varint,1,opt,name=level,proto3,enum=signal.SignalLevel_Level" json:"level,omitempty"` // The level of the signal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalLevel) Reset() {
	*x = SignalLevel{}
	mi := &file_signal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalLevel) ProtoMessage() {}

func (x *SignalLevel) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalLevel.ProtoReflect.Descriptor instead.
func (*SignalLevel) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{13}
}

func (x *SignalLevel) GetLevel() SignalLevel_Level {
	if x != nil {
		return x.Level
	}
	return SignalLevel_UNSPECIFIED
}

var File_signal_proto protoreflect.FileDescriptor

const file_signal_proto_rawDesc = "" +
	"\n" +
	"\fsignal.proto\x12\x06signal\x1a\vitems.proto\"z\n" +
	"\x10AddSignalRequest\x128\n" +
	"\n" +
	"properties\x18\x01 \x01(\v2\x18.signal.SignalPropertiesR\n" +
	"properties\x12,\n" +
	"\x12change_external_id\x18\x02 \x01(\fR\x10changeExternalId\";\n" +
	"\x11AddSignalResponse\x12&\n" +
	"\x06signal\x18\x01 \x01(\v2\x0e.signal.SignalR\x06signal\"S\n" +
	"#GetSignalsByChangeExternalIDRequest\x12,\n" +
	"\x12change_external_id\x18\x01 \x01(\fR\x10changeExternalId\"P\n" +
	"$GetSignalsByChangeExternalIDResponse\x12(\n" +
	"\asignals\x18\x01 \x03(\v2\x0e.signal.SignalR\asignals\"O\n" +
	"\x1fGetChangeOverviewSignalsRequest\x12,\n" +
	"\x12change_external_id\x18\x01 \x01(\fR\x10changeExternalId\"L\n" +
	" GetChangeOverviewSignalsResponse\x12(\n" +
	"\asignals\x18\x01 \x03(\v2\x0e.signal.SignalR\asignals\"E\n" +
	"\x15GetItemSignalsRequest\x12,\n" +
	"\x12change_external_id\x18\x02 \x01(\fR\x10changeExternalId\"B\n" +
	"\x16GetItemSignalsResponse\x12(\n" +
	"\asignals\x18\x01 \x03(\v2\x0e.signal.SignalR\asignals\"k\n" +
	"\x1bGetItemSignalDetailsRequest\x12\x1e\n" +
	"\x04item\x18\x01 \x01(\v2\n" +
	".ReferenceR\x04item\x12,\n" +
	"\x12change_external_id\x18\x02 \x01(\fR\x10changeExternalId\"H\n" +
	"\x1cGetItemSignalDetailsResponse\x12(\n" +
	"\asignals\x18\x01 \x03(\v2\x0e.signal.SignalR\asignals\"J\n" +
	"\x0eSignalMetadata\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12$\n" +
	"\raggregationID\x18\x02 \x01(\tR\raggregationID\"\xa8\x01\n" +
	"\x10SignalProperties\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12#\n" +
	"\x04item\x18\x05 \x01(\v2\n" +
	".ReferenceH\x00R\x04item\x88\x01\x01B\a\n" +
	"\x05_item\"v\n" +
	"\x06Signal\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.signal.SignalMetadataR\bmetadata\x128\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x18.signal.SignalPropertiesR\n" +
	"properties\"z\n" +
	"\vSignalLevel\x12/\n" +
	"\x05level\x18\x01 \x01(\x0e2\x19.signal.SignalLevel.LevelR\x05level\":\n" +
	"\x05Level\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CHANGE\x10\x01\x12\b\n" +
	"\x04ITEM\x10\x02\x12\n" +
	"\n" +
	"\x06DETAIL\x10\x032\xef\x03\n" +
	"\rSignalService\x12@\n" +
	"\tAddSignal\x12\x18.signal.AddSignalRequest\x1a\x19.signal.AddSignalResponse\x12y\n" +
	"\x1cGetSignalsByChangeExternalID\x12+.signal.GetSignalsByChangeExternalIDRequest\x1a,.signal.GetSignalsByChangeExternalIDResponse\x12m\n" +
	"\x18GetChangeOverviewSignals\x12'.signal.GetChangeOverviewSignalsRequest\x1a(.signal.GetChangeOverviewSignalsResponse\x12O\n" +
	"\x0eGetItemSignals\x12\x1d.signal.GetItemSignalsRequest\x1a\x1e.signal.GetItemSignalsResponse\x12a\n" +
	"\x14GetItemSignalDetails\x12#.signal.GetItemSignalDetailsRequest\x1a$.signal.GetItemSignalDetailsResponseB.Z,github.com/overmindtech/workspace/sdp-go;sdpb\x06proto3"

var (
	file_signal_proto_rawDescOnce sync.Once
	file_signal_proto_rawDescData []byte
)

func file_signal_proto_rawDescGZIP() []byte {
	file_signal_proto_rawDescOnce.Do(func() {
		file_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)))
	})
	return file_signal_proto_rawDescData
}

var file_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_signal_proto_goTypes = []any{
	(SignalLevel_Level)(0),                       // 0: signal.SignalLevel.Level
	(*AddSignalRequest)(nil),                     // 1: signal.AddSignalRequest
	(*AddSignalResponse)(nil),                    // 2: signal.AddSignalResponse
	(*GetSignalsByChangeExternalIDRequest)(nil),  // 3: signal.GetSignalsByChangeExternalIDRequest
	(*GetSignalsByChangeExternalIDResponse)(nil), // 4: signal.GetSignalsByChangeExternalIDResponse
	(*GetChangeOverviewSignalsRequest)(nil),      // 5: signal.GetChangeOverviewSignalsRequest
	(*GetChangeOverviewSignalsResponse)(nil),     // 6: signal.GetChangeOverviewSignalsResponse
	(*GetItemSignalsRequest)(nil),                // 7: signal.GetItemSignalsRequest
	(*GetItemSignalsResponse)(nil),               // 8: signal.GetItemSignalsResponse
	(*GetItemSignalDetailsRequest)(nil),          // 9: signal.GetItemSignalDetailsRequest
	(*GetItemSignalDetailsResponse)(nil),         // 10: signal.GetItemSignalDetailsResponse
	(*SignalMetadata)(nil),                       // 11: signal.SignalMetadata
	(*SignalProperties)(nil),                     // 12: signal.SignalProperties
	(*Signal)(nil),                               // 13: signal.Signal
	(*SignalLevel)(nil),                          // 14: signal.SignalLevel
	(*Reference)(nil),                            // 15: Reference
}
var file_signal_proto_depIdxs = []int32{
	12, // 0: signal.AddSignalRequest.properties:type_name -> signal.SignalProperties
	13, // 1: signal.AddSignalResponse.signal:type_name -> signal.Signal
	13, // 2: signal.GetSignalsByChangeExternalIDResponse.signals:type_name -> signal.Signal
	13, // 3: signal.GetChangeOverviewSignalsResponse.signals:type_name -> signal.Signal
	13, // 4: signal.GetItemSignalsResponse.signals:type_name -> signal.Signal
	15, // 5: signal.GetItemSignalDetailsRequest.item:type_name -> Reference
	13, // 6: signal.GetItemSignalDetailsResponse.signals:type_name -> signal.Signal
	15, // 7: signal.SignalProperties.item:type_name -> Reference
	11, // 8: signal.Signal.metadata:type_name -> signal.SignalMetadata
	12, // 9: signal.Signal.properties:type_name -> signal.SignalProperties
	0,  // 10: signal.SignalLevel.level:type_name -> signal.SignalLevel.Level
	1,  // 11: signal.SignalService.AddSignal:input_type -> signal.AddSignalRequest
	3,  // 12: signal.SignalService.GetSignalsByChangeExternalID:input_type -> signal.GetSignalsByChangeExternalIDRequest
	5,  // 13: signal.SignalService.GetChangeOverviewSignals:input_type -> signal.GetChangeOverviewSignalsRequest
	7,  // 14: signal.SignalService.GetItemSignals:input_type -> signal.GetItemSignalsRequest
	9,  // 15: signal.SignalService.GetItemSignalDetails:input_type -> signal.GetItemSignalDetailsRequest
	2,  // 16: signal.SignalService.AddSignal:output_type -> signal.AddSignalResponse
	4,  // 17: signal.SignalService.GetSignalsByChangeExternalID:output_type -> signal.GetSignalsByChangeExternalIDResponse
	6,  // 18: signal.SignalService.GetChangeOverviewSignals:output_type -> signal.GetChangeOverviewSignalsResponse
	8,  // 19: signal.SignalService.GetItemSignals:output_type -> signal.GetItemSignalsResponse
	10, // 20: signal.SignalService.GetItemSignalDetails:output_type -> signal.GetItemSignalDetailsResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_signal_proto_init() }
func file_signal_proto_init() {
	if File_signal_proto != nil {
		return
	}
	file_items_proto_init()
	file_signal_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signal_proto_goTypes,
		DependencyIndexes: file_signal_proto_depIdxs,
		EnumInfos:         file_signal_proto_enumTypes,
		MessageInfos:      file_signal_proto_msgTypes,
	}.Build()
	File_signal_proto = out.File
	file_signal_proto_goTypes = nil
	file_signal_proto_depIdxs = nil
}
