// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: snapshots.proto

package sdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *SnapshotMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Properties    *SnapshotProperties    `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Snapshot) GetProperties() *SnapshotProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type SnapshotProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of this snapshot
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description of this snapshot
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// queries that make up the snapshot
	Queries []*Query `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	// items stored in the snapshot
	Items []*Item `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	// edges stored in the snapshot
	Edges         []*Edge `protobuf:"bytes,6,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotProperties) Reset() {
	*x = SnapshotProperties{}
	mi := &file_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotProperties) ProtoMessage() {}

func (x *SnapshotProperties) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotProperties.ProtoReflect.Descriptor instead.
func (*SnapshotProperties) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotProperties) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotProperties) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SnapshotProperties) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *SnapshotProperties) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SnapshotProperties) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type SnapshotMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique id to identify this snapshot
	UUID []byte `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// timestamp when this snapshot was created
	Created       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotMetadata) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *SnapshotMetadata) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

// lists all snapshots
type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_snapshots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{3}
}

type ListSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the list of all snapshots
	Snapshots     []*Snapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotResponse) Reset() {
	*x = ListSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotResponse) ProtoMessage() {}

func (x *ListSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{4}
}

func (x *ListSnapshotResponse) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// creates a new snapshot
type CreateSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// properties of the new snapshot
	Properties    *SnapshotProperties `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSnapshotRequest) GetProperties() *SnapshotProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type CreateSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the newly created snapshot
	Snapshot      *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// get the details of a specific snapshot
type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{7}
}

func (x *GetSnapshotRequest) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{8}
}

func (x *GetSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// updates the properties of an existing snapshot
type UpdateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Properties    *SnapshotProperties    `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnapshotRequest) Reset() {
	*x = UpdateSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnapshotRequest) ProtoMessage() {}

func (x *UpdateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*UpdateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSnapshotRequest) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *UpdateSnapshotRequest) GetProperties() *SnapshotProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UpdateSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the updated version of the snapshot
	Snapshot      *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnapshotResponse) Reset() {
	*x = UpdateSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnapshotResponse) ProtoMessage() {}

func (x *UpdateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*UpdateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// deletes a given snapshot
type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSnapshotRequest) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{12}
}

// get the initial data
type GetInitialDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitialDataRequest) Reset() {
	*x = GetInitialDataRequest{}
	mi := &file_snapshots_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialDataRequest) ProtoMessage() {}

func (x *GetInitialDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialDataRequest.ProtoReflect.Descriptor instead.
func (*GetInitialDataRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{13}
}

type GetInitialDataResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BlastRadiusSnapshot   *Snapshot              `protobuf:"bytes,1,opt,name=blastRadiusSnapshot,proto3" json:"blastRadiusSnapshot,omitempty"`
	ChangingItemsBookmark *Bookmark              `protobuf:"bytes,2,opt,name=changingItemsBookmark,proto3" json:"changingItemsBookmark,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetInitialDataResponse) Reset() {
	*x = GetInitialDataResponse{}
	mi := &file_snapshots_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialDataResponse) ProtoMessage() {}

func (x *GetInitialDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialDataResponse.ProtoReflect.Descriptor instead.
func (*GetInitialDataResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{14}
}

func (x *GetInitialDataResponse) GetBlastRadiusSnapshot() *Snapshot {
	if x != nil {
		return x.BlastRadiusSnapshot
	}
	return nil
}

func (x *GetInitialDataResponse) GetChangingItemsBookmark() *Bookmark {
	if x != nil {
		return x.ChangingItemsBookmark
	}
	return nil
}

type ListSnapshotsByGUNRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GloballyUniqueName string                 `protobuf:"bytes,1,opt,name=globallyUniqueName,proto3" json:"globallyUniqueName,omitempty"`
	Pagination         *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListSnapshotsByGUNRequest) Reset() {
	*x = ListSnapshotsByGUNRequest{}
	mi := &file_snapshots_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsByGUNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsByGUNRequest) ProtoMessage() {}

func (x *ListSnapshotsByGUNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsByGUNRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsByGUNRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{15}
}

func (x *ListSnapshotsByGUNRequest) GetGloballyUniqueName() string {
	if x != nil {
		return x.GloballyUniqueName
	}
	return ""
}

func (x *ListSnapshotsByGUNRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListSnapshotsByGUNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUIDs         [][]byte               `protobuf:"bytes,1,rep,name=UUIDs,proto3" json:"UUIDs,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsByGUNResponse) Reset() {
	*x = ListSnapshotsByGUNResponse{}
	mi := &file_snapshots_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsByGUNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsByGUNResponse) ProtoMessage() {}

func (x *ListSnapshotsByGUNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsByGUNResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsByGUNResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{16}
}

func (x *ListSnapshotsByGUNResponse) GetUUIDs() [][]byte {
	if x != nil {
		return x.UUIDs
	}
	return nil
}

func (x *ListSnapshotsByGUNResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_snapshots_proto protoreflect.FileDescriptor

const file_snapshots_proto_rawDesc = "" +
	"\n" +
	"\x0fsnapshots.proto\x12\tsnapshots\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fbookmarks.proto\x1a\vitems.proto\x1a\n" +
	"util.proto\"\x82\x01\n" +
	"\bSnapshot\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.snapshots.SnapshotMetadataR\bmetadata\x12=\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x1d.snapshots.SnapshotPropertiesR\n" +
	"properties\"\xac\x01\n" +
	"\x12SnapshotProperties\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\aqueries\x18\x03 \x03(\v2\x06.QueryR\aqueries\x12\x1b\n" +
	"\x05items\x18\x05 \x03(\v2\x05.ItemR\x05items\x12\x1b\n" +
	"\x05edges\x18\x06 \x03(\v2\x05.EdgeR\x05edgesJ\x04\b\x04\x10\x05\"\\\n" +
	"\x10SnapshotMetadata\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\"\x16\n" +
	"\x14ListSnapshotsRequest\"I\n" +
	"\x14ListSnapshotResponse\x121\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x13.snapshots.SnapshotR\tsnapshots\"V\n" +
	"\x15CreateSnapshotRequest\x12=\n" +
	"\n" +
	"properties\x18\x01 \x01(\v2\x1d.snapshots.SnapshotPropertiesR\n" +
	"properties\"I\n" +
	"\x16CreateSnapshotResponse\x12/\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x13.snapshots.SnapshotR\bsnapshot\"(\n" +
	"\x12GetSnapshotRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\"F\n" +
	"\x13GetSnapshotResponse\x12/\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x13.snapshots.SnapshotR\bsnapshot\"j\n" +
	"\x15UpdateSnapshotRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12=\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x1d.snapshots.SnapshotPropertiesR\n" +
	"properties\"I\n" +
	"\x16UpdateSnapshotResponse\x12/\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x13.snapshots.SnapshotR\bsnapshot\"+\n" +
	"\x15DeleteSnapshotRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\"\x18\n" +
	"\x16DeleteSnapshotResponse\"\x17\n" +
	"\x15GetInitialDataRequest\"\xaa\x01\n" +
	"\x16GetInitialDataResponse\x12E\n" +
	"\x13blastRadiusSnapshot\x18\x01 \x01(\v2\x13.snapshots.SnapshotR\x13blastRadiusSnapshot\x12I\n" +
	"\x15changingItemsBookmark\x18\x02 \x01(\v2\x13.bookmarks.BookmarkR\x15changingItemsBookmark\"\x7f\n" +
	"\x19ListSnapshotsByGUNRequest\x12.\n" +
	"\x12globallyUniqueName\x18\x01 \x01(\tR\x12globallyUniqueName\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.PaginationRequestR\n" +
	"pagination\"g\n" +
	"\x1aListSnapshotsByGUNResponse\x12\x14\n" +
	"\x05UUIDs\x18\x01 \x03(\fR\x05UUIDs\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.PaginationResponseR\n" +
	"pagination2\x9a\x04\n" +
	"\x10SnapshotsService\x12Q\n" +
	"\rListSnapshots\x12\x1f.snapshots.ListSnapshotsRequest\x1a\x1f.snapshots.ListSnapshotResponse\x12U\n" +
	"\x0eCreateSnapshot\x12 .snapshots.CreateSnapshotRequest\x1a!.snapshots.CreateSnapshotResponse\x12L\n" +
	"\vGetSnapshot\x12\x1d.snapshots.GetSnapshotRequest\x1a\x1e.snapshots.GetSnapshotResponse\x12U\n" +
	"\x0eUpdateSnapshot\x12 .snapshots.UpdateSnapshotRequest\x1a!.snapshots.UpdateSnapshotResponse\x12U\n" +
	"\x0eDeleteSnapshot\x12 .snapshots.DeleteSnapshotRequest\x1a!.snapshots.DeleteSnapshotResponse\x12`\n" +
	"\x11ListSnapshotByGUN\x12$.snapshots.ListSnapshotsByGUNRequest\x1a%.snapshots.ListSnapshotsByGUNResponseB.Z,github.com/overmindtech/workspace/sdp-go;sdpb\x06proto3"

var (
	file_snapshots_proto_rawDescOnce sync.Once
	file_snapshots_proto_rawDescData []byte
)

func file_snapshots_proto_rawDescGZIP() []byte {
	file_snapshots_proto_rawDescOnce.Do(func() {
		file_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshots_proto_rawDesc), len(file_snapshots_proto_rawDesc)))
	})
	return file_snapshots_proto_rawDescData
}

var file_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_snapshots_proto_goTypes = []any{
	(*Snapshot)(nil),                   // 0: snapshots.Snapshot
	(*SnapshotProperties)(nil),         // 1: snapshots.SnapshotProperties
	(*SnapshotMetadata)(nil),           // 2: snapshots.SnapshotMetadata
	(*ListSnapshotsRequest)(nil),       // 3: snapshots.ListSnapshotsRequest
	(*ListSnapshotResponse)(nil),       // 4: snapshots.ListSnapshotResponse
	(*CreateSnapshotRequest)(nil),      // 5: snapshots.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),     // 6: snapshots.CreateSnapshotResponse
	(*GetSnapshotRequest)(nil),         // 7: snapshots.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),        // 8: snapshots.GetSnapshotResponse
	(*UpdateSnapshotRequest)(nil),      // 9: snapshots.UpdateSnapshotRequest
	(*UpdateSnapshotResponse)(nil),     // 10: snapshots.UpdateSnapshotResponse
	(*DeleteSnapshotRequest)(nil),      // 11: snapshots.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),     // 12: snapshots.DeleteSnapshotResponse
	(*GetInitialDataRequest)(nil),      // 13: snapshots.GetInitialDataRequest
	(*GetInitialDataResponse)(nil),     // 14: snapshots.GetInitialDataResponse
	(*ListSnapshotsByGUNRequest)(nil),  // 15: snapshots.ListSnapshotsByGUNRequest
	(*ListSnapshotsByGUNResponse)(nil), // 16: snapshots.ListSnapshotsByGUNResponse
	(*Query)(nil),                      // 17: Query
	(*Item)(nil),                       // 18: Item
	(*Edge)(nil),                       // 19: Edge
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
	(*Bookmark)(nil),                   // 21: bookmarks.Bookmark
	(*PaginationRequest)(nil),          // 22: PaginationRequest
	(*PaginationResponse)(nil),         // 23: PaginationResponse
}
var file_snapshots_proto_depIdxs = []int32{
	2,  // 0: snapshots.Snapshot.metadata:type_name -> snapshots.SnapshotMetadata
	1,  // 1: snapshots.Snapshot.properties:type_name -> snapshots.SnapshotProperties
	17, // 2: snapshots.SnapshotProperties.queries:type_name -> Query
	18, // 3: snapshots.SnapshotProperties.items:type_name -> Item
	19, // 4: snapshots.SnapshotProperties.edges:type_name -> Edge
	20, // 5: snapshots.SnapshotMetadata.created:type_name -> google.protobuf.Timestamp
	0,  // 6: snapshots.ListSnapshotResponse.snapshots:type_name -> snapshots.Snapshot
	1,  // 7: snapshots.CreateSnapshotRequest.properties:type_name -> snapshots.SnapshotProperties
	0,  // 8: snapshots.CreateSnapshotResponse.snapshot:type_name -> snapshots.Snapshot
	0,  // 9: snapshots.GetSnapshotResponse.snapshot:type_name -> snapshots.Snapshot
	1,  // 10: snapshots.UpdateSnapshotRequest.properties:type_name -> snapshots.SnapshotProperties
	0,  // 11: snapshots.UpdateSnapshotResponse.snapshot:type_name -> snapshots.Snapshot
	0,  // 12: snapshots.GetInitialDataResponse.blastRadiusSnapshot:type_name -> snapshots.Snapshot
	21, // 13: snapshots.GetInitialDataResponse.changingItemsBookmark:type_name -> bookmarks.Bookmark
	22, // 14: snapshots.ListSnapshotsByGUNRequest.pagination:type_name -> PaginationRequest
	23, // 15: snapshots.ListSnapshotsByGUNResponse.pagination:type_name -> PaginationResponse
	3,  // 16: snapshots.SnapshotsService.ListSnapshots:input_type -> snapshots.ListSnapshotsRequest
	5,  // 17: snapshots.SnapshotsService.CreateSnapshot:input_type -> snapshots.CreateSnapshotRequest
	7,  // 18: snapshots.SnapshotsService.GetSnapshot:input_type -> snapshots.GetSnapshotRequest
	9,  // 19: snapshots.SnapshotsService.UpdateSnapshot:input_type -> snapshots.UpdateSnapshotRequest
	11, // 20: snapshots.SnapshotsService.DeleteSnapshot:input_type -> snapshots.DeleteSnapshotRequest
	15, // 21: snapshots.SnapshotsService.ListSnapshotByGUN:input_type -> snapshots.ListSnapshotsByGUNRequest
	4,  // 22: snapshots.SnapshotsService.ListSnapshots:output_type -> snapshots.ListSnapshotResponse
	6,  // 23: snapshots.SnapshotsService.CreateSnapshot:output_type -> snapshots.CreateSnapshotResponse
	8,  // 24: snapshots.SnapshotsService.GetSnapshot:output_type -> snapshots.GetSnapshotResponse
	10, // 25: snapshots.SnapshotsService.UpdateSnapshot:output_type -> snapshots.UpdateSnapshotResponse
	12, // 26: snapshots.SnapshotsService.DeleteSnapshot:output_type -> snapshots.DeleteSnapshotResponse
	16, // 27: snapshots.SnapshotsService.ListSnapshotByGUN:output_type -> snapshots.ListSnapshotsByGUNResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_snapshots_proto_init() }
func file_snapshots_proto_init() {
	if File_snapshots_proto != nil {
		return
	}
	file_bookmarks_proto_init()
	file_items_proto_init()
	file_util_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshots_proto_rawDesc), len(file_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshots_proto_goTypes,
		DependencyIndexes: file_snapshots_proto_depIdxs,
		MessageInfos:      file_snapshots_proto_msgTypes,
	}.Build()
	File_snapshots_proto = out.File
	file_snapshots_proto_goTypes = nil
	file_snapshots_proto_depIdxs = nil
}
