// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: util.proto

package sdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_ALPHABETICAL_ASCENDING  SortOrder = 0 // A-Z
	SortOrder_ALPHABETICAL_DESCENDING SortOrder = 1 // Z-A
	SortOrder_DATE_ASCENDING          SortOrder = 2 // Oldest first
	SortOrder_DATE_DESCENDING         SortOrder = 3 // Newest first
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "ALPHABETICAL_ASCENDING",
		1: "ALPHABETICAL_DESCENDING",
		2: "DATE_ASCENDING",
		3: "DATE_DESCENDING",
	}
	SortOrder_value = map[string]int32{
		"ALPHABETICAL_ASCENDING":  0,
		"ALPHABETICAL_DESCENDING": 1,
		"DATE_ASCENDING":          2,
		"DATE_DESCENDING":         3,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_util_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_util_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

type PaginationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of items to return in a single page. The minimum is 10 and the
	// maximum is 100.
	PageSize int32 `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// The page number to return. the first page is 1. If the page number is
	// larger than the total number of pages, the last page is returned. If the
	// page number is negative, the first page 1 is returned.
	Page          int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_util_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type PaginationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of items in the current page
	PageSize int32 `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// The total number of items available. Expensive to calculate
	// https://www.cybertec-postgresql.com/en/pagination-problem-total-result-count/
	// this is done as a separate query
	TotalItems int32 `protobuf:"varint,2,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	// The current page number, NB if the user provided a negative page number,
	// this will be 1, if the user provided a page number larger than the total
	// number of pages, this will be the last page. If there are no results at
	// all, this will be 0.
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// The total number of pages available. based on the totalItems and pageSize.
	// If there are no results this will be zero.
	TotalPages    int32 `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_util_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_util_proto protoreflect.FileDescriptor

const file_util_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"util.proto\"C\n" +
	"\x11PaginationRequest\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"\x84\x01\n" +
	"\x12PaginationResponse\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"totalItems\x18\x02 \x01(\x05R\n" +
	"totalItems\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x04 \x01(\x05R\n" +
	"totalPages*m\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16ALPHABETICAL_ASCENDING\x10\x00\x12\x1b\n" +
	"\x17ALPHABETICAL_DESCENDING\x10\x01\x12\x12\n" +
	"\x0eDATE_ASCENDING\x10\x02\x12\x13\n" +
	"\x0fDATE_DESCENDING\x10\x03B.Z,github.com/overmindtech/workspace/sdp-go;sdpb\x06proto3"

var (
	file_util_proto_rawDescOnce sync.Once
	file_util_proto_rawDescData []byte
)

func file_util_proto_rawDescGZIP() []byte {
	file_util_proto_rawDescOnce.Do(func() {
		file_util_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)))
	})
	return file_util_proto_rawDescData
}

var file_util_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_util_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_util_proto_goTypes = []any{
	(SortOrder)(0),             // 0: SortOrder
	(*PaginationRequest)(nil),  // 1: PaginationRequest
	(*PaginationResponse)(nil), // 2: PaginationResponse
}
var file_util_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_util_proto_init() }
func file_util_proto_init() {
	if File_util_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_proto_goTypes,
		DependencyIndexes: file_util_proto_depIdxs,
		EnumInfos:         file_util_proto_enumTypes,
		MessageInfos:      file_util_proto_msgTypes,
	}.Build()
	File_util_proto = out.File
	file_util_proto_goTypes = nil
	file_util_proto_depIdxs = nil
}
