// Code generated by MockGen. DO NOT EDIT.
// Source: sources/azure/clients/gallery-images-client.go
//
// Generated by this command:
//
//	mockgen -destination=sources/azure/manual/mock_gallery_images_client_test.go -package=manual -source=sources/azure/clients/gallery-images-client.go
//

// Package manual is a generated GoMock package.
package manual

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockGalleryImagesClient is a mock of GalleryImagesClient interface.
type MockGalleryImagesClient struct {
	ctrl     *gomock.Controller
	recorder *MockGalleryImagesClientMockRecorder
	isgomock struct{}
}

// MockGalleryImagesClientMockRecorder is the mock recorder for MockGalleryImagesClient.
type MockGalleryImagesClientMockRecorder struct {
	mock *MockGalleryImagesClient
}

// NewMockGalleryImagesClient creates a new mock instance.
func NewMockGalleryImagesClient(ctrl *gomock.Controller) *MockGalleryImagesClient {
	mock := &MockGalleryImagesClient{ctrl: ctrl}
	mock.recorder = &MockGalleryImagesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGalleryImagesClient) EXPECT() *MockGalleryImagesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGalleryImagesClient) Get(ctx context.Context, resourceGroupName, galleryName, galleryImageName string, options *armcompute.GalleryImagesClientGetOptions) (armcompute.GalleryImagesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, galleryName, galleryImageName, options)
	ret0, _ := ret[0].(armcompute.GalleryImagesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGalleryImagesClientMockRecorder) Get(ctx, resourceGroupName, galleryName, galleryImageName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGalleryImagesClient)(nil).Get), ctx, resourceGroupName, galleryName, galleryImageName, options)
}

// NewListByGalleryPager mocks base method.
func (m *MockGalleryImagesClient) NewListByGalleryPager(resourceGroupName, galleryName string, options *armcompute.GalleryImagesClientListByGalleryOptions) clients.GalleryImagesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByGalleryPager", resourceGroupName, galleryName, options)
	ret0, _ := ret[0].(clients.GalleryImagesPager)
	return ret0
}

// NewListByGalleryPager indicates an expected call of NewListByGalleryPager.
func (mr *MockGalleryImagesClientMockRecorder) NewListByGalleryPager(resourceGroupName, galleryName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByGalleryPager", reflect.TypeOf((*MockGalleryImagesClient)(nil).NewListByGalleryPager), resourceGroupName, galleryName, options)
}
