// Code generated by MockGen. DO NOT EDIT.
// Source: virtual-machine-extensions-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_virtual_machine_extensions_client.go -package=mocks -source=virtual-machine-extensions-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockVirtualMachineExtensionsClient is a mock of VirtualMachineExtensionsClient interface.
type MockVirtualMachineExtensionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachineExtensionsClientMockRecorder
	isgomock struct{}
}

// MockVirtualMachineExtensionsClientMockRecorder is the mock recorder for MockVirtualMachineExtensionsClient.
type MockVirtualMachineExtensionsClientMockRecorder struct {
	mock *MockVirtualMachineExtensionsClient
}

// NewMockVirtualMachineExtensionsClient creates a new mock instance.
func NewMockVirtualMachineExtensionsClient(ctrl *gomock.Controller) *MockVirtualMachineExtensionsClient {
	mock := &MockVirtualMachineExtensionsClient{ctrl: ctrl}
	mock.recorder = &MockVirtualMachineExtensionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachineExtensionsClient) EXPECT() *MockVirtualMachineExtensionsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVirtualMachineExtensionsClient) Get(ctx context.Context, resourceGroupName, virtualMachineName, vmExtensionName string, options *armcompute.VirtualMachineExtensionsClientGetOptions) (armcompute.VirtualMachineExtensionsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, virtualMachineName, vmExtensionName, options)
	ret0, _ := ret[0].(armcompute.VirtualMachineExtensionsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVirtualMachineExtensionsClientMockRecorder) Get(ctx, resourceGroupName, virtualMachineName, vmExtensionName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVirtualMachineExtensionsClient)(nil).Get), ctx, resourceGroupName, virtualMachineName, vmExtensionName, options)
}

// List mocks base method.
func (m *MockVirtualMachineExtensionsClient) List(ctx context.Context, resourceGroupName, virtualMachineName string, options *armcompute.VirtualMachineExtensionsClientListOptions) (armcompute.VirtualMachineExtensionsClientListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, resourceGroupName, virtualMachineName, options)
	ret0, _ := ret[0].(armcompute.VirtualMachineExtensionsClientListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVirtualMachineExtensionsClientMockRecorder) List(ctx, resourceGroupName, virtualMachineName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVirtualMachineExtensionsClient)(nil).List), ctx, resourceGroupName, virtualMachineName, options)
}
