// Code generated by MockGen. DO NOT EDIT.
// Source: managed-hsms-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_managed_hsms_client.go -package=mocks -source=managed-hsms-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armkeyvault "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockManagedHSMsClient is a mock of ManagedHSMsClient interface.
type MockManagedHSMsClient struct {
	ctrl     *gomock.Controller
	recorder *MockManagedHSMsClientMockRecorder
	isgomock struct{}
}

// MockManagedHSMsClientMockRecorder is the mock recorder for MockManagedHSMsClient.
type MockManagedHSMsClientMockRecorder struct {
	mock *MockManagedHSMsClient
}

// NewMockManagedHSMsClient creates a new mock instance.
func NewMockManagedHSMsClient(ctrl *gomock.Controller) *MockManagedHSMsClient {
	mock := &MockManagedHSMsClient{ctrl: ctrl}
	mock.recorder = &MockManagedHSMsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagedHSMsClient) EXPECT() *MockManagedHSMsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockManagedHSMsClient) Get(ctx context.Context, resourceGroupName, name string, options *armkeyvault.ManagedHsmsClientGetOptions) (armkeyvault.ManagedHsmsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, name, options)
	ret0, _ := ret[0].(armkeyvault.ManagedHsmsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockManagedHSMsClientMockRecorder) Get(ctx, resourceGroupName, name, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManagedHSMsClient)(nil).Get), ctx, resourceGroupName, name, options)
}

// NewListByResourceGroupPager mocks base method.
func (m *MockManagedHSMsClient) NewListByResourceGroupPager(resourceGroupName string, options *armkeyvault.ManagedHsmsClientListByResourceGroupOptions) clients.ManagedHSMsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByResourceGroupPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.ManagedHSMsPager)
	return ret0
}

// NewListByResourceGroupPager indicates an expected call of NewListByResourceGroupPager.
func (mr *MockManagedHSMsClientMockRecorder) NewListByResourceGroupPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByResourceGroupPager", reflect.TypeOf((*MockManagedHSMsClient)(nil).NewListByResourceGroupPager), resourceGroupName, options)
}
