// Code generated by MockGen. DO NOT EDIT.
// Source: elastic-san-volume-group-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_elastic_san_volume_group_client.go -package=mocks -source=elastic-san-volume-group-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armelasticsan "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/elasticsan/armelasticsan"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockElasticSanVolumeGroupClient is a mock of ElasticSanVolumeGroupClient interface.
type MockElasticSanVolumeGroupClient struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSanVolumeGroupClientMockRecorder
	isgomock struct{}
}

// MockElasticSanVolumeGroupClientMockRecorder is the mock recorder for MockElasticSanVolumeGroupClient.
type MockElasticSanVolumeGroupClientMockRecorder struct {
	mock *MockElasticSanVolumeGroupClient
}

// NewMockElasticSanVolumeGroupClient creates a new mock instance.
func NewMockElasticSanVolumeGroupClient(ctrl *gomock.Controller) *MockElasticSanVolumeGroupClient {
	mock := &MockElasticSanVolumeGroupClient{ctrl: ctrl}
	mock.recorder = &MockElasticSanVolumeGroupClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElasticSanVolumeGroupClient) EXPECT() *MockElasticSanVolumeGroupClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockElasticSanVolumeGroupClient) Get(ctx context.Context, resourceGroupName, elasticSanName, volumeGroupName string, options *armelasticsan.VolumeGroupsClientGetOptions) (armelasticsan.VolumeGroupsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, elasticSanName, volumeGroupName, options)
	ret0, _ := ret[0].(armelasticsan.VolumeGroupsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockElasticSanVolumeGroupClientMockRecorder) Get(ctx, resourceGroupName, elasticSanName, volumeGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockElasticSanVolumeGroupClient)(nil).Get), ctx, resourceGroupName, elasticSanName, volumeGroupName, options)
}

// NewListByElasticSanPager mocks base method.
func (m *MockElasticSanVolumeGroupClient) NewListByElasticSanPager(resourceGroupName, elasticSanName string, options *armelasticsan.VolumeGroupsClientListByElasticSanOptions) clients.ElasticSanVolumeGroupPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByElasticSanPager", resourceGroupName, elasticSanName, options)
	ret0, _ := ret[0].(clients.ElasticSanVolumeGroupPager)
	return ret0
}

// NewListByElasticSanPager indicates an expected call of NewListByElasticSanPager.
func (mr *MockElasticSanVolumeGroupClientMockRecorder) NewListByElasticSanPager(resourceGroupName, elasticSanName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByElasticSanPager", reflect.TypeOf((*MockElasticSanVolumeGroupClient)(nil).NewListByElasticSanPager), resourceGroupName, elasticSanName, options)
}
