// Code generated by MockGen. DO NOT EDIT.
// Source: proximity-placement-groups-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_proximity_placement_groups_client.go -package=mocks -source=proximity-placement-groups-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockProximityPlacementGroupsClient is a mock of ProximityPlacementGroupsClient interface.
type MockProximityPlacementGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockProximityPlacementGroupsClientMockRecorder
	isgomock struct{}
}

// MockProximityPlacementGroupsClientMockRecorder is the mock recorder for MockProximityPlacementGroupsClient.
type MockProximityPlacementGroupsClientMockRecorder struct {
	mock *MockProximityPlacementGroupsClient
}

// NewMockProximityPlacementGroupsClient creates a new mock instance.
func NewMockProximityPlacementGroupsClient(ctrl *gomock.Controller) *MockProximityPlacementGroupsClient {
	mock := &MockProximityPlacementGroupsClient{ctrl: ctrl}
	mock.recorder = &MockProximityPlacementGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProximityPlacementGroupsClient) EXPECT() *MockProximityPlacementGroupsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProximityPlacementGroupsClient) Get(ctx context.Context, resourceGroupName, proximityPlacementGroupName string, options *armcompute.ProximityPlacementGroupsClientGetOptions) (armcompute.ProximityPlacementGroupsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, proximityPlacementGroupName, options)
	ret0, _ := ret[0].(armcompute.ProximityPlacementGroupsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProximityPlacementGroupsClientMockRecorder) Get(ctx, resourceGroupName, proximityPlacementGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProximityPlacementGroupsClient)(nil).Get), ctx, resourceGroupName, proximityPlacementGroupName, options)
}

// ListByResourceGroup mocks base method.
func (m *MockProximityPlacementGroupsClient) ListByResourceGroup(ctx context.Context, resourceGroupName string, options *armcompute.ProximityPlacementGroupsClientListByResourceGroupOptions) clients.ProximityPlacementGroupsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByResourceGroup", ctx, resourceGroupName, options)
	ret0, _ := ret[0].(clients.ProximityPlacementGroupsPager)
	return ret0
}

// ListByResourceGroup indicates an expected call of ListByResourceGroup.
func (mr *MockProximityPlacementGroupsClientMockRecorder) ListByResourceGroup(ctx, resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByResourceGroup", reflect.TypeOf((*MockProximityPlacementGroupsClient)(nil).ListByResourceGroup), ctx, resourceGroupName, options)
}
