// Code generated by MockGen. DO NOT EDIT.
// Source: sql-databases-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_sql_databases_client.go -package=mocks -source=sql-databases-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armsql "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql/v2"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockSqlDatabasesClient is a mock of SqlDatabasesClient interface.
type MockSqlDatabasesClient struct {
	ctrl     *gomock.Controller
	recorder *MockSqlDatabasesClientMockRecorder
	isgomock struct{}
}

// MockSqlDatabasesClientMockRecorder is the mock recorder for MockSqlDatabasesClient.
type MockSqlDatabasesClientMockRecorder struct {
	mock *MockSqlDatabasesClient
}

// NewMockSqlDatabasesClient creates a new mock instance.
func NewMockSqlDatabasesClient(ctrl *gomock.Controller) *MockSqlDatabasesClient {
	mock := &MockSqlDatabasesClient{ctrl: ctrl}
	mock.recorder = &MockSqlDatabasesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSqlDatabasesClient) EXPECT() *MockSqlDatabasesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSqlDatabasesClient) Get(ctx context.Context, resourceGroupName, serverName, databaseName string) (armsql.DatabasesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, databaseName)
	ret0, _ := ret[0].(armsql.DatabasesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSqlDatabasesClientMockRecorder) Get(ctx, resourceGroupName, serverName, databaseName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSqlDatabasesClient)(nil).Get), ctx, resourceGroupName, serverName, databaseName)
}

// ListByServer mocks base method.
func (m *MockSqlDatabasesClient) ListByServer(ctx context.Context, resourceGroupName, serverName string) clients.SqlDatabasesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByServer", ctx, resourceGroupName, serverName)
	ret0, _ := ret[0].(clients.SqlDatabasesPager)
	return ret0
}

// ListByServer indicates an expected call of ListByServer.
func (mr *MockSqlDatabasesClientMockRecorder) ListByServer(ctx, resourceGroupName, serverName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByServer", reflect.TypeOf((*MockSqlDatabasesClient)(nil).ListByServer), ctx, resourceGroupName, serverName)
}
