// Code generated by MockGen. DO NOT EDIT.
// Source: dedicated-host-groups-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_dedicated_host_groups_client.go -package=mocks -source=dedicated-host-groups-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockDedicatedHostGroupsClient is a mock of DedicatedHostGroupsClient interface.
type MockDedicatedHostGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDedicatedHostGroupsClientMockRecorder
	isgomock struct{}
}

// MockDedicatedHostGroupsClientMockRecorder is the mock recorder for MockDedicatedHostGroupsClient.
type MockDedicatedHostGroupsClientMockRecorder struct {
	mock *MockDedicatedHostGroupsClient
}

// NewMockDedicatedHostGroupsClient creates a new mock instance.
func NewMockDedicatedHostGroupsClient(ctrl *gomock.Controller) *MockDedicatedHostGroupsClient {
	mock := &MockDedicatedHostGroupsClient{ctrl: ctrl}
	mock.recorder = &MockDedicatedHostGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDedicatedHostGroupsClient) EXPECT() *MockDedicatedHostGroupsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDedicatedHostGroupsClient) Get(ctx context.Context, resourceGroupName, dedicatedHostGroupName string, options *armcompute.DedicatedHostGroupsClientGetOptions) (armcompute.DedicatedHostGroupsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, dedicatedHostGroupName, options)
	ret0, _ := ret[0].(armcompute.DedicatedHostGroupsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDedicatedHostGroupsClientMockRecorder) Get(ctx, resourceGroupName, dedicatedHostGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDedicatedHostGroupsClient)(nil).Get), ctx, resourceGroupName, dedicatedHostGroupName, options)
}

// NewListByResourceGroupPager mocks base method.
func (m *MockDedicatedHostGroupsClient) NewListByResourceGroupPager(resourceGroupName string, options *armcompute.DedicatedHostGroupsClientListByResourceGroupOptions) clients.DedicatedHostGroupsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByResourceGroupPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.DedicatedHostGroupsPager)
	return ret0
}

// NewListByResourceGroupPager indicates an expected call of NewListByResourceGroupPager.
func (mr *MockDedicatedHostGroupsClientMockRecorder) NewListByResourceGroupPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByResourceGroupPager", reflect.TypeOf((*MockDedicatedHostGroupsClient)(nil).NewListByResourceGroupPager), resourceGroupName, options)
}
