// Code generated by MockGen. DO NOT EDIT.
// Source: blob-containers-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_blob_containers_client.go -package=mocks -source=blob-containers-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armstorage "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/v2"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockBlobContainersClient is a mock of BlobContainersClient interface.
type MockBlobContainersClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlobContainersClientMockRecorder
	isgomock struct{}
}

// MockBlobContainersClientMockRecorder is the mock recorder for MockBlobContainersClient.
type MockBlobContainersClientMockRecorder struct {
	mock *MockBlobContainersClient
}

// NewMockBlobContainersClient creates a new mock instance.
func NewMockBlobContainersClient(ctrl *gomock.Controller) *MockBlobContainersClient {
	mock := &MockBlobContainersClient{ctrl: ctrl}
	mock.recorder = &MockBlobContainersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobContainersClient) EXPECT() *MockBlobContainersClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBlobContainersClient) Get(ctx context.Context, resourceGroupName, accountName, containerName string) (armstorage.BlobContainersClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, accountName, containerName)
	ret0, _ := ret[0].(armstorage.BlobContainersClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBlobContainersClientMockRecorder) Get(ctx, resourceGroupName, accountName, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBlobContainersClient)(nil).Get), ctx, resourceGroupName, accountName, containerName)
}

// List mocks base method.
func (m *MockBlobContainersClient) List(ctx context.Context, resourceGroupName, accountName string) clients.BlobContainersPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, resourceGroupName, accountName)
	ret0, _ := ret[0].(clients.BlobContainersPager)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockBlobContainersClientMockRecorder) List(ctx, resourceGroupName, accountName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBlobContainersClient)(nil).List), ctx, resourceGroupName, accountName)
}
