// Code generated by MockGen. DO NOT EDIT.
// Source: dbforpostgresql-flexible-server-virtual-endpoint-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_dbforpostgresql_flexible_server_virtual_endpoint_client.go -package=mocks -source=dbforpostgresql-flexible-server-virtual-endpoint-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armpostgresqlflexibleservers "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v5"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockDBforPostgreSQLFlexibleServerVirtualEndpointClient is a mock of DBforPostgreSQLFlexibleServerVirtualEndpointClient interface.
type MockDBforPostgreSQLFlexibleServerVirtualEndpointClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBforPostgreSQLFlexibleServerVirtualEndpointClientMockRecorder
	isgomock struct{}
}

// MockDBforPostgreSQLFlexibleServerVirtualEndpointClientMockRecorder is the mock recorder for MockDBforPostgreSQLFlexibleServerVirtualEndpointClient.
type MockDBforPostgreSQLFlexibleServerVirtualEndpointClientMockRecorder struct {
	mock *MockDBforPostgreSQLFlexibleServerVirtualEndpointClient
}

// NewMockDBforPostgreSQLFlexibleServerVirtualEndpointClient creates a new mock instance.
func NewMockDBforPostgreSQLFlexibleServerVirtualEndpointClient(ctrl *gomock.Controller) *MockDBforPostgreSQLFlexibleServerVirtualEndpointClient {
	mock := &MockDBforPostgreSQLFlexibleServerVirtualEndpointClient{ctrl: ctrl}
	mock.recorder = &MockDBforPostgreSQLFlexibleServerVirtualEndpointClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBforPostgreSQLFlexibleServerVirtualEndpointClient) EXPECT() *MockDBforPostgreSQLFlexibleServerVirtualEndpointClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerVirtualEndpointClient) Get(ctx context.Context, resourceGroupName, serverName, virtualEndpointName string) (armpostgresqlflexibleservers.VirtualEndpointsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, virtualEndpointName)
	ret0, _ := ret[0].(armpostgresqlflexibleservers.VirtualEndpointsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBforPostgreSQLFlexibleServerVirtualEndpointClientMockRecorder) Get(ctx, resourceGroupName, serverName, virtualEndpointName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerVirtualEndpointClient)(nil).Get), ctx, resourceGroupName, serverName, virtualEndpointName)
}

// ListByServer mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerVirtualEndpointClient) ListByServer(ctx context.Context, resourceGroupName, serverName string) clients.DBforPostgreSQLFlexibleServerVirtualEndpointPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByServer", ctx, resourceGroupName, serverName)
	ret0, _ := ret[0].(clients.DBforPostgreSQLFlexibleServerVirtualEndpointPager)
	return ret0
}

// ListByServer indicates an expected call of ListByServer.
func (mr *MockDBforPostgreSQLFlexibleServerVirtualEndpointClientMockRecorder) ListByServer(ctx, resourceGroupName, serverName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByServer", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerVirtualEndpointClient)(nil).ListByServer), ctx, resourceGroupName, serverName)
}
