// Code generated by MockGen. DO NOT EDIT.
// Source: virtual-network-gateway-connections-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_virtual_network_gateway_connections_client.go -package=mocks -source=virtual-network-gateway-connections-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v9"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockVirtualNetworkGatewayConnectionsClient is a mock of VirtualNetworkGatewayConnectionsClient interface.
type MockVirtualNetworkGatewayConnectionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualNetworkGatewayConnectionsClientMockRecorder
	isgomock struct{}
}

// MockVirtualNetworkGatewayConnectionsClientMockRecorder is the mock recorder for MockVirtualNetworkGatewayConnectionsClient.
type MockVirtualNetworkGatewayConnectionsClientMockRecorder struct {
	mock *MockVirtualNetworkGatewayConnectionsClient
}

// NewMockVirtualNetworkGatewayConnectionsClient creates a new mock instance.
func NewMockVirtualNetworkGatewayConnectionsClient(ctrl *gomock.Controller) *MockVirtualNetworkGatewayConnectionsClient {
	mock := &MockVirtualNetworkGatewayConnectionsClient{ctrl: ctrl}
	mock.recorder = &MockVirtualNetworkGatewayConnectionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualNetworkGatewayConnectionsClient) EXPECT() *MockVirtualNetworkGatewayConnectionsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVirtualNetworkGatewayConnectionsClient) Get(ctx context.Context, resourceGroupName, virtualNetworkGatewayConnectionName string, options *armnetwork.VirtualNetworkGatewayConnectionsClientGetOptions) (armnetwork.VirtualNetworkGatewayConnectionsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, virtualNetworkGatewayConnectionName, options)
	ret0, _ := ret[0].(armnetwork.VirtualNetworkGatewayConnectionsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVirtualNetworkGatewayConnectionsClientMockRecorder) Get(ctx, resourceGroupName, virtualNetworkGatewayConnectionName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVirtualNetworkGatewayConnectionsClient)(nil).Get), ctx, resourceGroupName, virtualNetworkGatewayConnectionName, options)
}

// NewListPager mocks base method.
func (m *MockVirtualNetworkGatewayConnectionsClient) NewListPager(resourceGroupName string, options *armnetwork.VirtualNetworkGatewayConnectionsClientListOptions) clients.VirtualNetworkGatewayConnectionsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.VirtualNetworkGatewayConnectionsPager)
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockVirtualNetworkGatewayConnectionsClientMockRecorder) NewListPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockVirtualNetworkGatewayConnectionsClient)(nil).NewListPager), resourceGroupName, options)
}
