// Code generated by MockGen. DO NOT EDIT.
// Source: application-gateways-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_application_gateways_client.go -package=mocks -source=application-gateways-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v6"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationGatewaysClient is a mock of ApplicationGatewaysClient interface.
type MockApplicationGatewaysClient struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationGatewaysClientMockRecorder
	isgomock struct{}
}

// MockApplicationGatewaysClientMockRecorder is the mock recorder for MockApplicationGatewaysClient.
type MockApplicationGatewaysClientMockRecorder struct {
	mock *MockApplicationGatewaysClient
}

// NewMockApplicationGatewaysClient creates a new mock instance.
func NewMockApplicationGatewaysClient(ctrl *gomock.Controller) *MockApplicationGatewaysClient {
	mock := &MockApplicationGatewaysClient{ctrl: ctrl}
	mock.recorder = &MockApplicationGatewaysClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationGatewaysClient) EXPECT() *MockApplicationGatewaysClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockApplicationGatewaysClient) Get(ctx context.Context, resourceGroupName, applicationGatewayName string, options *armnetwork.ApplicationGatewaysClientGetOptions) (armnetwork.ApplicationGatewaysClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, applicationGatewayName, options)
	ret0, _ := ret[0].(armnetwork.ApplicationGatewaysClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApplicationGatewaysClientMockRecorder) Get(ctx, resourceGroupName, applicationGatewayName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApplicationGatewaysClient)(nil).Get), ctx, resourceGroupName, applicationGatewayName, options)
}

// List mocks base method.
func (m *MockApplicationGatewaysClient) List(resourceGroupName string, options *armnetwork.ApplicationGatewaysClientListOptions) clients.ApplicationGatewaysPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", resourceGroupName, options)
	ret0, _ := ret[0].(clients.ApplicationGatewaysPager)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockApplicationGatewaysClientMockRecorder) List(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApplicationGatewaysClient)(nil).List), resourceGroupName, options)
}
