// Code generated by MockGen. DO NOT EDIT.
// Source: security-rules-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_security_rules_client.go -package=mocks -source=security-rules-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v9"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityRulesClient is a mock of SecurityRulesClient interface.
type MockSecurityRulesClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityRulesClientMockRecorder
	isgomock struct{}
}

// MockSecurityRulesClientMockRecorder is the mock recorder for MockSecurityRulesClient.
type MockSecurityRulesClientMockRecorder struct {
	mock *MockSecurityRulesClient
}

// NewMockSecurityRulesClient creates a new mock instance.
func NewMockSecurityRulesClient(ctrl *gomock.Controller) *MockSecurityRulesClient {
	mock := &MockSecurityRulesClient{ctrl: ctrl}
	mock.recorder = &MockSecurityRulesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityRulesClient) EXPECT() *MockSecurityRulesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSecurityRulesClient) Get(ctx context.Context, resourceGroupName, networkSecurityGroupName, securityRuleName string, options *armnetwork.SecurityRulesClientGetOptions) (armnetwork.SecurityRulesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, networkSecurityGroupName, securityRuleName, options)
	ret0, _ := ret[0].(armnetwork.SecurityRulesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecurityRulesClientMockRecorder) Get(ctx, resourceGroupName, networkSecurityGroupName, securityRuleName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSecurityRulesClient)(nil).Get), ctx, resourceGroupName, networkSecurityGroupName, securityRuleName, options)
}

// NewListPager mocks base method.
func (m *MockSecurityRulesClient) NewListPager(resourceGroupName, networkSecurityGroupName string, options *armnetwork.SecurityRulesClientListOptions) clients.SecurityRulesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", resourceGroupName, networkSecurityGroupName, options)
	ret0, _ := ret[0].(clients.SecurityRulesPager)
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockSecurityRulesClientMockRecorder) NewListPager(resourceGroupName, networkSecurityGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockSecurityRulesClient)(nil).NewListPager), resourceGroupName, networkSecurityGroupName, options)
}
