// Code generated by MockGen. DO NOT EDIT.
// Source: network-security-groups-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_network_security_groups_client.go -package=mocks -source=network-security-groups-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v8"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkSecurityGroupsClient is a mock of NetworkSecurityGroupsClient interface.
type MockNetworkSecurityGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkSecurityGroupsClientMockRecorder
	isgomock struct{}
}

// MockNetworkSecurityGroupsClientMockRecorder is the mock recorder for MockNetworkSecurityGroupsClient.
type MockNetworkSecurityGroupsClientMockRecorder struct {
	mock *MockNetworkSecurityGroupsClient
}

// NewMockNetworkSecurityGroupsClient creates a new mock instance.
func NewMockNetworkSecurityGroupsClient(ctrl *gomock.Controller) *MockNetworkSecurityGroupsClient {
	mock := &MockNetworkSecurityGroupsClient{ctrl: ctrl}
	mock.recorder = &MockNetworkSecurityGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkSecurityGroupsClient) EXPECT() *MockNetworkSecurityGroupsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockNetworkSecurityGroupsClient) Get(ctx context.Context, resourceGroupName, networkSecurityGroupName string, options *armnetwork.SecurityGroupsClientGetOptions) (armnetwork.SecurityGroupsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, networkSecurityGroupName, options)
	ret0, _ := ret[0].(armnetwork.SecurityGroupsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNetworkSecurityGroupsClientMockRecorder) Get(ctx, resourceGroupName, networkSecurityGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNetworkSecurityGroupsClient)(nil).Get), ctx, resourceGroupName, networkSecurityGroupName, options)
}

// List mocks base method.
func (m *MockNetworkSecurityGroupsClient) List(ctx context.Context, resourceGroupName string, options *armnetwork.SecurityGroupsClientListOptions) clients.NetworkSecurityGroupsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, resourceGroupName, options)
	ret0, _ := ret[0].(clients.NetworkSecurityGroupsPager)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockNetworkSecurityGroupsClientMockRecorder) List(ctx, resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNetworkSecurityGroupsClient)(nil).List), ctx, resourceGroupName, options)
}
