// Code generated by MockGen. DO NOT EDIT.
// Source: dbforpostgresql-flexible-server-administrator-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_dbforpostgresql_flexible_server_administrator_client.go -package=mocks -source=dbforpostgresql-flexible-server-administrator-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armpostgresqlflexibleservers "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v5"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockDBforPostgreSQLFlexibleServerAdministratorClient is a mock of DBforPostgreSQLFlexibleServerAdministratorClient interface.
type MockDBforPostgreSQLFlexibleServerAdministratorClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBforPostgreSQLFlexibleServerAdministratorClientMockRecorder
	isgomock struct{}
}

// MockDBforPostgreSQLFlexibleServerAdministratorClientMockRecorder is the mock recorder for MockDBforPostgreSQLFlexibleServerAdministratorClient.
type MockDBforPostgreSQLFlexibleServerAdministratorClientMockRecorder struct {
	mock *MockDBforPostgreSQLFlexibleServerAdministratorClient
}

// NewMockDBforPostgreSQLFlexibleServerAdministratorClient creates a new mock instance.
func NewMockDBforPostgreSQLFlexibleServerAdministratorClient(ctrl *gomock.Controller) *MockDBforPostgreSQLFlexibleServerAdministratorClient {
	mock := &MockDBforPostgreSQLFlexibleServerAdministratorClient{ctrl: ctrl}
	mock.recorder = &MockDBforPostgreSQLFlexibleServerAdministratorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBforPostgreSQLFlexibleServerAdministratorClient) EXPECT() *MockDBforPostgreSQLFlexibleServerAdministratorClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerAdministratorClient) Get(ctx context.Context, resourceGroupName, serverName, objectID string) (armpostgresqlflexibleservers.AdministratorsMicrosoftEntraClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, objectID)
	ret0, _ := ret[0].(armpostgresqlflexibleservers.AdministratorsMicrosoftEntraClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBforPostgreSQLFlexibleServerAdministratorClientMockRecorder) Get(ctx, resourceGroupName, serverName, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerAdministratorClient)(nil).Get), ctx, resourceGroupName, serverName, objectID)
}

// ListByServer mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerAdministratorClient) ListByServer(ctx context.Context, resourceGroupName, serverName string) clients.DBforPostgreSQLFlexibleServerAdministratorPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByServer", ctx, resourceGroupName, serverName)
	ret0, _ := ret[0].(clients.DBforPostgreSQLFlexibleServerAdministratorPager)
	return ret0
}

// ListByServer indicates an expected call of ListByServer.
func (mr *MockDBforPostgreSQLFlexibleServerAdministratorClientMockRecorder) ListByServer(ctx, resourceGroupName, serverName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByServer", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerAdministratorClient)(nil).ListByServer), ctx, resourceGroupName, serverName)
}
