// Code generated by MockGen. DO NOT EDIT.
// Source: postgresql-flexible-servers-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_postgresql_flexible_servers_client.go -package=mocks -source=postgresql-flexible-servers-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armpostgresqlflexibleservers "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v5"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockPostgreSQLFlexibleServersClient is a mock of PostgreSQLFlexibleServersClient interface.
type MockPostgreSQLFlexibleServersClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostgreSQLFlexibleServersClientMockRecorder
	isgomock struct{}
}

// MockPostgreSQLFlexibleServersClientMockRecorder is the mock recorder for MockPostgreSQLFlexibleServersClient.
type MockPostgreSQLFlexibleServersClientMockRecorder struct {
	mock *MockPostgreSQLFlexibleServersClient
}

// NewMockPostgreSQLFlexibleServersClient creates a new mock instance.
func NewMockPostgreSQLFlexibleServersClient(ctrl *gomock.Controller) *MockPostgreSQLFlexibleServersClient {
	mock := &MockPostgreSQLFlexibleServersClient{ctrl: ctrl}
	mock.recorder = &MockPostgreSQLFlexibleServersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgreSQLFlexibleServersClient) EXPECT() *MockPostgreSQLFlexibleServersClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPostgreSQLFlexibleServersClient) Get(ctx context.Context, resourceGroupName, serverName string, options *armpostgresqlflexibleservers.ServersClientGetOptions) (armpostgresqlflexibleservers.ServersClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, options)
	ret0, _ := ret[0].(armpostgresqlflexibleservers.ServersClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPostgreSQLFlexibleServersClientMockRecorder) Get(ctx, resourceGroupName, serverName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPostgreSQLFlexibleServersClient)(nil).Get), ctx, resourceGroupName, serverName, options)
}

// ListByResourceGroup mocks base method.
func (m *MockPostgreSQLFlexibleServersClient) ListByResourceGroup(ctx context.Context, resourceGroupName string, options *armpostgresqlflexibleservers.ServersClientListByResourceGroupOptions) clients.PostgreSQLFlexibleServersPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByResourceGroup", ctx, resourceGroupName, options)
	ret0, _ := ret[0].(clients.PostgreSQLFlexibleServersPager)
	return ret0
}

// ListByResourceGroup indicates an expected call of ListByResourceGroup.
func (mr *MockPostgreSQLFlexibleServersClientMockRecorder) ListByResourceGroup(ctx, resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByResourceGroup", reflect.TypeOf((*MockPostgreSQLFlexibleServersClient)(nil).ListByResourceGroup), ctx, resourceGroupName, options)
}
