// Code generated by MockGen. DO NOT EDIT.
// Source: compute-disk-access-private-endpoint-connection-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_compute_disk_access_private_endpoint_connection_client.go -package=mocks -source=compute-disk-access-private-endpoint-connection-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockComputeDiskAccessPrivateEndpointConnectionsClient is a mock of ComputeDiskAccessPrivateEndpointConnectionsClient interface.
type MockComputeDiskAccessPrivateEndpointConnectionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockComputeDiskAccessPrivateEndpointConnectionsClientMockRecorder
	isgomock struct{}
}

// MockComputeDiskAccessPrivateEndpointConnectionsClientMockRecorder is the mock recorder for MockComputeDiskAccessPrivateEndpointConnectionsClient.
type MockComputeDiskAccessPrivateEndpointConnectionsClientMockRecorder struct {
	mock *MockComputeDiskAccessPrivateEndpointConnectionsClient
}

// NewMockComputeDiskAccessPrivateEndpointConnectionsClient creates a new mock instance.
func NewMockComputeDiskAccessPrivateEndpointConnectionsClient(ctrl *gomock.Controller) *MockComputeDiskAccessPrivateEndpointConnectionsClient {
	mock := &MockComputeDiskAccessPrivateEndpointConnectionsClient{ctrl: ctrl}
	mock.recorder = &MockComputeDiskAccessPrivateEndpointConnectionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComputeDiskAccessPrivateEndpointConnectionsClient) EXPECT() *MockComputeDiskAccessPrivateEndpointConnectionsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockComputeDiskAccessPrivateEndpointConnectionsClient) Get(ctx context.Context, resourceGroupName, diskAccessName, privateEndpointConnectionName string) (armcompute.DiskAccessesClientGetAPrivateEndpointConnectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, diskAccessName, privateEndpointConnectionName)
	ret0, _ := ret[0].(armcompute.DiskAccessesClientGetAPrivateEndpointConnectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockComputeDiskAccessPrivateEndpointConnectionsClientMockRecorder) Get(ctx, resourceGroupName, diskAccessName, privateEndpointConnectionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockComputeDiskAccessPrivateEndpointConnectionsClient)(nil).Get), ctx, resourceGroupName, diskAccessName, privateEndpointConnectionName)
}

// NewListPrivateEndpointConnectionsPager mocks base method.
func (m *MockComputeDiskAccessPrivateEndpointConnectionsClient) NewListPrivateEndpointConnectionsPager(resourceGroupName, diskAccessName string, options *armcompute.DiskAccessesClientListPrivateEndpointConnectionsOptions) clients.ComputeDiskAccessPrivateEndpointConnectionsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPrivateEndpointConnectionsPager", resourceGroupName, diskAccessName, options)
	ret0, _ := ret[0].(clients.ComputeDiskAccessPrivateEndpointConnectionsPager)
	return ret0
}

// NewListPrivateEndpointConnectionsPager indicates an expected call of NewListPrivateEndpointConnectionsPager.
func (mr *MockComputeDiskAccessPrivateEndpointConnectionsClientMockRecorder) NewListPrivateEndpointConnectionsPager(resourceGroupName, diskAccessName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPrivateEndpointConnectionsPager", reflect.TypeOf((*MockComputeDiskAccessPrivateEndpointConnectionsClient)(nil).NewListPrivateEndpointConnectionsPager), resourceGroupName, diskAccessName, options)
}
