// Code generated by MockGen. DO NOT EDIT.
// Source: elastic-san-volume-snapshot-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_elastic_san_volume_snapshot_client.go -package=mocks -source=elastic-san-volume-snapshot-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armelasticsan "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/elasticsan/armelasticsan"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockElasticSanVolumeSnapshotClient is a mock of ElasticSanVolumeSnapshotClient interface.
type MockElasticSanVolumeSnapshotClient struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSanVolumeSnapshotClientMockRecorder
	isgomock struct{}
}

// MockElasticSanVolumeSnapshotClientMockRecorder is the mock recorder for MockElasticSanVolumeSnapshotClient.
type MockElasticSanVolumeSnapshotClientMockRecorder struct {
	mock *MockElasticSanVolumeSnapshotClient
}

// NewMockElasticSanVolumeSnapshotClient creates a new mock instance.
func NewMockElasticSanVolumeSnapshotClient(ctrl *gomock.Controller) *MockElasticSanVolumeSnapshotClient {
	mock := &MockElasticSanVolumeSnapshotClient{ctrl: ctrl}
	mock.recorder = &MockElasticSanVolumeSnapshotClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElasticSanVolumeSnapshotClient) EXPECT() *MockElasticSanVolumeSnapshotClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockElasticSanVolumeSnapshotClient) Get(ctx context.Context, resourceGroupName, elasticSanName, volumeGroupName, snapshotName string, options *armelasticsan.VolumeSnapshotsClientGetOptions) (armelasticsan.VolumeSnapshotsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, elasticSanName, volumeGroupName, snapshotName, options)
	ret0, _ := ret[0].(armelasticsan.VolumeSnapshotsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockElasticSanVolumeSnapshotClientMockRecorder) Get(ctx, resourceGroupName, elasticSanName, volumeGroupName, snapshotName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockElasticSanVolumeSnapshotClient)(nil).Get), ctx, resourceGroupName, elasticSanName, volumeGroupName, snapshotName, options)
}

// ListByVolumeGroup mocks base method.
func (m *MockElasticSanVolumeSnapshotClient) ListByVolumeGroup(ctx context.Context, resourceGroupName, elasticSanName, volumeGroupName string, options *armelasticsan.VolumeSnapshotsClientListByVolumeGroupOptions) clients.ElasticSanVolumeSnapshotPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVolumeGroup", ctx, resourceGroupName, elasticSanName, volumeGroupName, options)
	ret0, _ := ret[0].(clients.ElasticSanVolumeSnapshotPager)
	return ret0
}

// ListByVolumeGroup indicates an expected call of ListByVolumeGroup.
func (mr *MockElasticSanVolumeSnapshotClientMockRecorder) ListByVolumeGroup(ctx, resourceGroupName, elasticSanName, volumeGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVolumeGroup", reflect.TypeOf((*MockElasticSanVolumeSnapshotClient)(nil).ListByVolumeGroup), ctx, resourceGroupName, elasticSanName, volumeGroupName, options)
}
