// Code generated by MockGen. DO NOT EDIT.
// Source: availability-sets-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_availability_sets_client.go -package=mocks -source=availability-sets-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v6"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockAvailabilitySetsClient is a mock of AvailabilitySetsClient interface.
type MockAvailabilitySetsClient struct {
	ctrl     *gomock.Controller
	recorder *MockAvailabilitySetsClientMockRecorder
	isgomock struct{}
}

// MockAvailabilitySetsClientMockRecorder is the mock recorder for MockAvailabilitySetsClient.
type MockAvailabilitySetsClientMockRecorder struct {
	mock *MockAvailabilitySetsClient
}

// NewMockAvailabilitySetsClient creates a new mock instance.
func NewMockAvailabilitySetsClient(ctrl *gomock.Controller) *MockAvailabilitySetsClient {
	mock := &MockAvailabilitySetsClient{ctrl: ctrl}
	mock.recorder = &MockAvailabilitySetsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailabilitySetsClient) EXPECT() *MockAvailabilitySetsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAvailabilitySetsClient) Get(ctx context.Context, resourceGroupName, availabilitySetName string, options *armcompute.AvailabilitySetsClientGetOptions) (armcompute.AvailabilitySetsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, availabilitySetName, options)
	ret0, _ := ret[0].(armcompute.AvailabilitySetsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAvailabilitySetsClientMockRecorder) Get(ctx, resourceGroupName, availabilitySetName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAvailabilitySetsClient)(nil).Get), ctx, resourceGroupName, availabilitySetName, options)
}

// NewListPager mocks base method.
func (m *MockAvailabilitySetsClient) NewListPager(resourceGroupName string, options *armcompute.AvailabilitySetsClientListOptions) clients.AvailabilitySetsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.AvailabilitySetsPager)
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockAvailabilitySetsClientMockRecorder) NewListPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockAvailabilitySetsClient)(nil).NewListPager), resourceGroupName, options)
}
