// Code generated by MockGen. DO NOT EDIT.
// Source: postgresql-databases-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_postgresql_databases_client.go -package=mocks -source=postgresql-databases-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armpostgresqlflexibleservers "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v5"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockPostgreSQLDatabasesClient is a mock of PostgreSQLDatabasesClient interface.
type MockPostgreSQLDatabasesClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostgreSQLDatabasesClientMockRecorder
	isgomock struct{}
}

// MockPostgreSQLDatabasesClientMockRecorder is the mock recorder for MockPostgreSQLDatabasesClient.
type MockPostgreSQLDatabasesClientMockRecorder struct {
	mock *MockPostgreSQLDatabasesClient
}

// NewMockPostgreSQLDatabasesClient creates a new mock instance.
func NewMockPostgreSQLDatabasesClient(ctrl *gomock.Controller) *MockPostgreSQLDatabasesClient {
	mock := &MockPostgreSQLDatabasesClient{ctrl: ctrl}
	mock.recorder = &MockPostgreSQLDatabasesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgreSQLDatabasesClient) EXPECT() *MockPostgreSQLDatabasesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPostgreSQLDatabasesClient) Get(ctx context.Context, resourceGroupName, serverName, databaseName string) (armpostgresqlflexibleservers.DatabasesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, databaseName)
	ret0, _ := ret[0].(armpostgresqlflexibleservers.DatabasesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPostgreSQLDatabasesClientMockRecorder) Get(ctx, resourceGroupName, serverName, databaseName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPostgreSQLDatabasesClient)(nil).Get), ctx, resourceGroupName, serverName, databaseName)
}

// ListByServer mocks base method.
func (m *MockPostgreSQLDatabasesClient) ListByServer(ctx context.Context, resourceGroupName, serverName string) clients.PostgreSQLDatabasesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByServer", ctx, resourceGroupName, serverName)
	ret0, _ := ret[0].(clients.PostgreSQLDatabasesPager)
	return ret0
}

// ListByServer indicates an expected call of ListByServer.
func (mr *MockPostgreSQLDatabasesClientMockRecorder) ListByServer(ctx, resourceGroupName, serverName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByServer", reflect.TypeOf((*MockPostgreSQLDatabasesClient)(nil).ListByServer), ctx, resourceGroupName, serverName)
}
