// Code generated by MockGen. DO NOT EDIT.
// Source: images-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_images_client.go -package=mocks -source=images-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockImagesClient is a mock of ImagesClient interface.
type MockImagesClient struct {
	ctrl     *gomock.Controller
	recorder *MockImagesClientMockRecorder
	isgomock struct{}
}

// MockImagesClientMockRecorder is the mock recorder for MockImagesClient.
type MockImagesClientMockRecorder struct {
	mock *MockImagesClient
}

// NewMockImagesClient creates a new mock instance.
func NewMockImagesClient(ctrl *gomock.Controller) *MockImagesClient {
	mock := &MockImagesClient{ctrl: ctrl}
	mock.recorder = &MockImagesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImagesClient) EXPECT() *MockImagesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockImagesClient) Get(ctx context.Context, resourceGroupName, imageName string, options *armcompute.ImagesClientGetOptions) (armcompute.ImagesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, imageName, options)
	ret0, _ := ret[0].(armcompute.ImagesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockImagesClientMockRecorder) Get(ctx, resourceGroupName, imageName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockImagesClient)(nil).Get), ctx, resourceGroupName, imageName, options)
}

// NewListByResourceGroupPager mocks base method.
func (m *MockImagesClient) NewListByResourceGroupPager(resourceGroupName string, options *armcompute.ImagesClientListByResourceGroupOptions) clients.ImagesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByResourceGroupPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.ImagesPager)
	return ret0
}

// NewListByResourceGroupPager indicates an expected call of NewListByResourceGroupPager.
func (mr *MockImagesClientMockRecorder) NewListByResourceGroupPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByResourceGroupPager", reflect.TypeOf((*MockImagesClient)(nil).NewListByResourceGroupPager), resourceGroupName, options)
}
