// Code generated by MockGen. DO NOT EDIT.
// Source: dbforpostgresql-flexible-server-backup-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_dbforpostgresql_flexible_server_backup_client.go -package=mocks -source=dbforpostgresql-flexible-server-backup-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armpostgresqlflexibleservers "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v5"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockDBforPostgreSQLFlexibleServerBackupClient is a mock of DBforPostgreSQLFlexibleServerBackupClient interface.
type MockDBforPostgreSQLFlexibleServerBackupClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBforPostgreSQLFlexibleServerBackupClientMockRecorder
	isgomock struct{}
}

// MockDBforPostgreSQLFlexibleServerBackupClientMockRecorder is the mock recorder for MockDBforPostgreSQLFlexibleServerBackupClient.
type MockDBforPostgreSQLFlexibleServerBackupClientMockRecorder struct {
	mock *MockDBforPostgreSQLFlexibleServerBackupClient
}

// NewMockDBforPostgreSQLFlexibleServerBackupClient creates a new mock instance.
func NewMockDBforPostgreSQLFlexibleServerBackupClient(ctrl *gomock.Controller) *MockDBforPostgreSQLFlexibleServerBackupClient {
	mock := &MockDBforPostgreSQLFlexibleServerBackupClient{ctrl: ctrl}
	mock.recorder = &MockDBforPostgreSQLFlexibleServerBackupClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBforPostgreSQLFlexibleServerBackupClient) EXPECT() *MockDBforPostgreSQLFlexibleServerBackupClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerBackupClient) Get(ctx context.Context, resourceGroupName, serverName, backupName string) (armpostgresqlflexibleservers.BackupsAutomaticAndOnDemandClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, backupName)
	ret0, _ := ret[0].(armpostgresqlflexibleservers.BackupsAutomaticAndOnDemandClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBforPostgreSQLFlexibleServerBackupClientMockRecorder) Get(ctx, resourceGroupName, serverName, backupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerBackupClient)(nil).Get), ctx, resourceGroupName, serverName, backupName)
}

// ListByServer mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerBackupClient) ListByServer(ctx context.Context, resourceGroupName, serverName string) clients.DBforPostgreSQLFlexibleServerBackupPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByServer", ctx, resourceGroupName, serverName)
	ret0, _ := ret[0].(clients.DBforPostgreSQLFlexibleServerBackupPager)
	return ret0
}

// ListByServer indicates an expected call of ListByServer.
func (mr *MockDBforPostgreSQLFlexibleServerBackupClientMockRecorder) ListByServer(ctx, resourceGroupName, serverName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByServer", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerBackupClient)(nil).ListByServer), ctx, resourceGroupName, serverName)
}
