// Code generated by MockGen. DO NOT EDIT.
// Source: sql-elastic-pool-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_sql_elastic_pool_client.go -package=mocks -source=sql-elastic-pool-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armsql "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql/v2"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockSqlElasticPoolClient is a mock of SqlElasticPoolClient interface.
type MockSqlElasticPoolClient struct {
	ctrl     *gomock.Controller
	recorder *MockSqlElasticPoolClientMockRecorder
	isgomock struct{}
}

// MockSqlElasticPoolClientMockRecorder is the mock recorder for MockSqlElasticPoolClient.
type MockSqlElasticPoolClientMockRecorder struct {
	mock *MockSqlElasticPoolClient
}

// NewMockSqlElasticPoolClient creates a new mock instance.
func NewMockSqlElasticPoolClient(ctrl *gomock.Controller) *MockSqlElasticPoolClient {
	mock := &MockSqlElasticPoolClient{ctrl: ctrl}
	mock.recorder = &MockSqlElasticPoolClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSqlElasticPoolClient) EXPECT() *MockSqlElasticPoolClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSqlElasticPoolClient) Get(ctx context.Context, resourceGroupName, serverName, elasticPoolName string) (armsql.ElasticPoolsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, elasticPoolName)
	ret0, _ := ret[0].(armsql.ElasticPoolsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSqlElasticPoolClientMockRecorder) Get(ctx, resourceGroupName, serverName, elasticPoolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSqlElasticPoolClient)(nil).Get), ctx, resourceGroupName, serverName, elasticPoolName)
}

// ListByServer mocks base method.
func (m *MockSqlElasticPoolClient) ListByServer(ctx context.Context, resourceGroupName, serverName string) clients.SqlElasticPoolPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByServer", ctx, resourceGroupName, serverName)
	ret0, _ := ret[0].(clients.SqlElasticPoolPager)
	return ret0
}

// ListByServer indicates an expected call of ListByServer.
func (mr *MockSqlElasticPoolClientMockRecorder) ListByServer(ctx, resourceGroupName, serverName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByServer", reflect.TypeOf((*MockSqlElasticPoolClient)(nil).ListByServer), ctx, resourceGroupName, serverName)
}
