// Code generated by MockGen. DO NOT EDIT.
// Source: network-watchers-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_network_watchers_client.go -package=mocks -source=network-watchers-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v9"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkWatchersClient is a mock of NetworkWatchersClient interface.
type MockNetworkWatchersClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkWatchersClientMockRecorder
	isgomock struct{}
}

// MockNetworkWatchersClientMockRecorder is the mock recorder for MockNetworkWatchersClient.
type MockNetworkWatchersClientMockRecorder struct {
	mock *MockNetworkWatchersClient
}

// NewMockNetworkWatchersClient creates a new mock instance.
func NewMockNetworkWatchersClient(ctrl *gomock.Controller) *MockNetworkWatchersClient {
	mock := &MockNetworkWatchersClient{ctrl: ctrl}
	mock.recorder = &MockNetworkWatchersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkWatchersClient) EXPECT() *MockNetworkWatchersClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockNetworkWatchersClient) Get(ctx context.Context, resourceGroupName, networkWatcherName string, options *armnetwork.WatchersClientGetOptions) (armnetwork.WatchersClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, networkWatcherName, options)
	ret0, _ := ret[0].(armnetwork.WatchersClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNetworkWatchersClientMockRecorder) Get(ctx, resourceGroupName, networkWatcherName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNetworkWatchersClient)(nil).Get), ctx, resourceGroupName, networkWatcherName, options)
}

// NewListPager mocks base method.
func (m *MockNetworkWatchersClient) NewListPager(resourceGroupName string, options *armnetwork.WatchersClientListOptions) clients.NetworkWatchersPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.NetworkWatchersPager)
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockNetworkWatchersClientMockRecorder) NewListPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockNetworkWatchersClient)(nil).NewListPager), resourceGroupName, options)
}
