// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/overmindtech/cli/sources/azure/clients (interfaces: VirtualMachinesPagerInterface)
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_virtual_machines_pager.go -package=mocks github.com/overmindtech/cli/sources/azure/clients VirtualMachinesPagerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockVirtualMachinesPagerInterface is a mock of VirtualMachinesPagerInterface interface.
type MockVirtualMachinesPagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachinesPagerInterfaceMockRecorder
	isgomock struct{}
}

// MockVirtualMachinesPagerInterfaceMockRecorder is the mock recorder for MockVirtualMachinesPagerInterface.
type MockVirtualMachinesPagerInterfaceMockRecorder struct {
	mock *MockVirtualMachinesPagerInterface
}

// NewMockVirtualMachinesPagerInterface creates a new mock instance.
func NewMockVirtualMachinesPagerInterface(ctrl *gomock.Controller) *MockVirtualMachinesPagerInterface {
	mock := &MockVirtualMachinesPagerInterface{ctrl: ctrl}
	mock.recorder = &MockVirtualMachinesPagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachinesPagerInterface) EXPECT() *MockVirtualMachinesPagerInterfaceMockRecorder {
	return m.recorder
}

// More mocks base method.
func (m *MockVirtualMachinesPagerInterface) More() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "More")
	ret0, _ := ret[0].(bool)
	return ret0
}

// More indicates an expected call of More.
func (mr *MockVirtualMachinesPagerInterfaceMockRecorder) More() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "More", reflect.TypeOf((*MockVirtualMachinesPagerInterface)(nil).More))
}

// NextPage mocks base method.
func (m *MockVirtualMachinesPagerInterface) NextPage(ctx context.Context) (armcompute.VirtualMachinesClientListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPage", ctx)
	ret0, _ := ret[0].(armcompute.VirtualMachinesClientListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPage indicates an expected call of NextPage.
func (mr *MockVirtualMachinesPagerInterfaceMockRecorder) NextPage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MockVirtualMachinesPagerInterface)(nil).NextPage), ctx)
}
