// Code generated by MockGen. DO NOT EDIT.
// Source: dbforpostgresql-flexible-server-private-endpoint-connection-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_dbforpostgresql_flexible_server_private_endpoint_connection_client.go -package=mocks -source=dbforpostgresql-flexible-server-private-endpoint-connection-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armpostgresqlflexibleservers "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/v5"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient is a mock of DBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient interface.
type MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClientMockRecorder
	isgomock struct{}
}

// MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClientMockRecorder is the mock recorder for MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient.
type MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClientMockRecorder struct {
	mock *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient
}

// NewMockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient creates a new mock instance.
func NewMockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient(ctrl *gomock.Controller) *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient {
	mock := &MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient{ctrl: ctrl}
	mock.recorder = &MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient) EXPECT() *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient) Get(ctx context.Context, resourceGroupName, serverName, privateEndpointConnectionName string) (armpostgresqlflexibleservers.PrivateEndpointConnectionsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, serverName, privateEndpointConnectionName)
	ret0, _ := ret[0].(armpostgresqlflexibleservers.PrivateEndpointConnectionsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClientMockRecorder) Get(ctx, resourceGroupName, serverName, privateEndpointConnectionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient)(nil).Get), ctx, resourceGroupName, serverName, privateEndpointConnectionName)
}

// ListByServer mocks base method.
func (m *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient) ListByServer(ctx context.Context, resourceGroupName, serverName string) clients.DBforPostgreSQLFlexibleServerPrivateEndpointConnectionsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByServer", ctx, resourceGroupName, serverName)
	ret0, _ := ret[0].(clients.DBforPostgreSQLFlexibleServerPrivateEndpointConnectionsPager)
	return ret0
}

// ListByServer indicates an expected call of ListByServer.
func (mr *MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClientMockRecorder) ListByServer(ctx, resourceGroupName, serverName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByServer", reflect.TypeOf((*MockDBforPostgreSQLFlexibleServerPrivateEndpointConnectionsClient)(nil).ListByServer), ctx, resourceGroupName, serverName)
}
