// Code generated by MockGen. DO NOT EDIT.
// Source: virtual-machines-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_virtual_machines_client.go -package=mocks -source=virtual-machines-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockVirtualMachinesPager is a mock of VirtualMachinesPager interface.
type MockVirtualMachinesPager struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachinesPagerMockRecorder
	isgomock struct{}
}

// MockVirtualMachinesPagerMockRecorder is the mock recorder for MockVirtualMachinesPager.
type MockVirtualMachinesPagerMockRecorder struct {
	mock *MockVirtualMachinesPager
}

// NewMockVirtualMachinesPager creates a new mock instance.
func NewMockVirtualMachinesPager(ctrl *gomock.Controller) *MockVirtualMachinesPager {
	mock := &MockVirtualMachinesPager{ctrl: ctrl}
	mock.recorder = &MockVirtualMachinesPagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachinesPager) EXPECT() *MockVirtualMachinesPagerMockRecorder {
	return m.recorder
}

// More mocks base method.
func (m *MockVirtualMachinesPager) More() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "More")
	ret0, _ := ret[0].(bool)
	return ret0
}

// More indicates an expected call of More.
func (mr *MockVirtualMachinesPagerMockRecorder) More() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "More", reflect.TypeOf((*MockVirtualMachinesPager)(nil).More))
}

// NextPage mocks base method.
func (m *MockVirtualMachinesPager) NextPage(ctx context.Context) (armcompute.VirtualMachinesClientListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPage", ctx)
	ret0, _ := ret[0].(armcompute.VirtualMachinesClientListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPage indicates an expected call of NextPage.
func (mr *MockVirtualMachinesPagerMockRecorder) NextPage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MockVirtualMachinesPager)(nil).NextPage), ctx)
}

// MockVirtualMachinesClient is a mock of VirtualMachinesClient interface.
type MockVirtualMachinesClient struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachinesClientMockRecorder
	isgomock struct{}
}

// MockVirtualMachinesClientMockRecorder is the mock recorder for MockVirtualMachinesClient.
type MockVirtualMachinesClientMockRecorder struct {
	mock *MockVirtualMachinesClient
}

// NewMockVirtualMachinesClient creates a new mock instance.
func NewMockVirtualMachinesClient(ctrl *gomock.Controller) *MockVirtualMachinesClient {
	mock := &MockVirtualMachinesClient{ctrl: ctrl}
	mock.recorder = &MockVirtualMachinesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachinesClient) EXPECT() *MockVirtualMachinesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVirtualMachinesClient) Get(ctx context.Context, resourceGroupName, vmName string, options *armcompute.VirtualMachinesClientGetOptions) (armcompute.VirtualMachinesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, vmName, options)
	ret0, _ := ret[0].(armcompute.VirtualMachinesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVirtualMachinesClientMockRecorder) Get(ctx, resourceGroupName, vmName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVirtualMachinesClient)(nil).Get), ctx, resourceGroupName, vmName, options)
}

// NewListPager mocks base method.
func (m *MockVirtualMachinesClient) NewListPager(resourceGroupName string, options *armcompute.VirtualMachinesClientListOptions) clients.VirtualMachinesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.VirtualMachinesPager)
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockVirtualMachinesClientMockRecorder) NewListPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockVirtualMachinesClient)(nil).NewListPager), resourceGroupName, options)
}
