// Code generated by MockGen. DO NOT EDIT.
// Source: elastic-san-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_elastic_san_client.go -package=mocks -source=elastic-san-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armelasticsan "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/elasticsan/armelasticsan"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockElasticSanClient is a mock of ElasticSanClient interface.
type MockElasticSanClient struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSanClientMockRecorder
	isgomock struct{}
}

// MockElasticSanClientMockRecorder is the mock recorder for MockElasticSanClient.
type MockElasticSanClientMockRecorder struct {
	mock *MockElasticSanClient
}

// NewMockElasticSanClient creates a new mock instance.
func NewMockElasticSanClient(ctrl *gomock.Controller) *MockElasticSanClient {
	mock := &MockElasticSanClient{ctrl: ctrl}
	mock.recorder = &MockElasticSanClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElasticSanClient) EXPECT() *MockElasticSanClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockElasticSanClient) Get(ctx context.Context, resourceGroupName, elasticSanName string, options *armelasticsan.ElasticSansClientGetOptions) (armelasticsan.ElasticSansClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, elasticSanName, options)
	ret0, _ := ret[0].(armelasticsan.ElasticSansClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockElasticSanClientMockRecorder) Get(ctx, resourceGroupName, elasticSanName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockElasticSanClient)(nil).Get), ctx, resourceGroupName, elasticSanName, options)
}

// NewListByResourceGroupPager mocks base method.
func (m *MockElasticSanClient) NewListByResourceGroupPager(resourceGroupName string, options *armelasticsan.ElasticSansClientListByResourceGroupOptions) clients.ElasticSanPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByResourceGroupPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.ElasticSanPager)
	return ret0
}

// NewListByResourceGroupPager indicates an expected call of NewListByResourceGroupPager.
func (mr *MockElasticSanClientMockRecorder) NewListByResourceGroupPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByResourceGroupPager", reflect.TypeOf((*MockElasticSanClient)(nil).NewListByResourceGroupPager), resourceGroupName, options)
}
