// Code generated by MockGen. DO NOT EDIT.
// Source: zones-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_zones_client.go -package=mocks -source=zones-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armdns "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockZonesClient is a mock of ZonesClient interface.
type MockZonesClient struct {
	ctrl     *gomock.Controller
	recorder *MockZonesClientMockRecorder
	isgomock struct{}
}

// MockZonesClientMockRecorder is the mock recorder for MockZonesClient.
type MockZonesClientMockRecorder struct {
	mock *MockZonesClient
}

// NewMockZonesClient creates a new mock instance.
func NewMockZonesClient(ctrl *gomock.Controller) *MockZonesClient {
	mock := &MockZonesClient{ctrl: ctrl}
	mock.recorder = &MockZonesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZonesClient) EXPECT() *MockZonesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockZonesClient) Get(ctx context.Context, resourceGroupName, zoneName string, options *armdns.ZonesClientGetOptions) (armdns.ZonesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, zoneName, options)
	ret0, _ := ret[0].(armdns.ZonesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockZonesClientMockRecorder) Get(ctx, resourceGroupName, zoneName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockZonesClient)(nil).Get), ctx, resourceGroupName, zoneName, options)
}

// NewListByResourceGroupPager mocks base method.
func (m *MockZonesClient) NewListByResourceGroupPager(resourceGroupName string, options *armdns.ZonesClientListByResourceGroupOptions) clients.ZonesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByResourceGroupPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.ZonesPager)
	return ret0
}

// NewListByResourceGroupPager indicates an expected call of NewListByResourceGroupPager.
func (mr *MockZonesClientMockRecorder) NewListByResourceGroupPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByResourceGroupPager", reflect.TypeOf((*MockZonesClient)(nil).NewListByResourceGroupPager), resourceGroupName, options)
}
