// Code generated by MockGen. DO NOT EDIT.
// Source: application-security-groups-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_application_security_groups_client.go -package=mocks -source=application-security-groups-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v9"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationSecurityGroupsClient is a mock of ApplicationSecurityGroupsClient interface.
type MockApplicationSecurityGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationSecurityGroupsClientMockRecorder
	isgomock struct{}
}

// MockApplicationSecurityGroupsClientMockRecorder is the mock recorder for MockApplicationSecurityGroupsClient.
type MockApplicationSecurityGroupsClientMockRecorder struct {
	mock *MockApplicationSecurityGroupsClient
}

// NewMockApplicationSecurityGroupsClient creates a new mock instance.
func NewMockApplicationSecurityGroupsClient(ctrl *gomock.Controller) *MockApplicationSecurityGroupsClient {
	mock := &MockApplicationSecurityGroupsClient{ctrl: ctrl}
	mock.recorder = &MockApplicationSecurityGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationSecurityGroupsClient) EXPECT() *MockApplicationSecurityGroupsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockApplicationSecurityGroupsClient) Get(ctx context.Context, resourceGroupName, applicationSecurityGroupName string, options *armnetwork.ApplicationSecurityGroupsClientGetOptions) (armnetwork.ApplicationSecurityGroupsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, applicationSecurityGroupName, options)
	ret0, _ := ret[0].(armnetwork.ApplicationSecurityGroupsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApplicationSecurityGroupsClientMockRecorder) Get(ctx, resourceGroupName, applicationSecurityGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApplicationSecurityGroupsClient)(nil).Get), ctx, resourceGroupName, applicationSecurityGroupName, options)
}

// NewListPager mocks base method.
func (m *MockApplicationSecurityGroupsClient) NewListPager(resourceGroupName string, options *armnetwork.ApplicationSecurityGroupsClientListOptions) clients.ApplicationSecurityGroupsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.ApplicationSecurityGroupsPager)
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockApplicationSecurityGroupsClientMockRecorder) NewListPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockApplicationSecurityGroupsClient)(nil).NewListPager), resourceGroupName, options)
}
