// Code generated by MockGen. DO NOT EDIT.
// Source: shared-gallery-images-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_shared_gallery_images_client.go -package=mocks -source=shared-gallery-images-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v7"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockSharedGalleryImagesClient is a mock of SharedGalleryImagesClient interface.
type MockSharedGalleryImagesClient struct {
	ctrl     *gomock.Controller
	recorder *MockSharedGalleryImagesClientMockRecorder
	isgomock struct{}
}

// MockSharedGalleryImagesClientMockRecorder is the mock recorder for MockSharedGalleryImagesClient.
type MockSharedGalleryImagesClientMockRecorder struct {
	mock *MockSharedGalleryImagesClient
}

// NewMockSharedGalleryImagesClient creates a new mock instance.
func NewMockSharedGalleryImagesClient(ctrl *gomock.Controller) *MockSharedGalleryImagesClient {
	mock := &MockSharedGalleryImagesClient{ctrl: ctrl}
	mock.recorder = &MockSharedGalleryImagesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSharedGalleryImagesClient) EXPECT() *MockSharedGalleryImagesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSharedGalleryImagesClient) Get(ctx context.Context, location, galleryUniqueName, galleryImageName string, options *armcompute.SharedGalleryImagesClientGetOptions) (armcompute.SharedGalleryImagesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, location, galleryUniqueName, galleryImageName, options)
	ret0, _ := ret[0].(armcompute.SharedGalleryImagesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSharedGalleryImagesClientMockRecorder) Get(ctx, location, galleryUniqueName, galleryImageName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSharedGalleryImagesClient)(nil).Get), ctx, location, galleryUniqueName, galleryImageName, options)
}

// NewListPager mocks base method.
func (m *MockSharedGalleryImagesClient) NewListPager(location, galleryUniqueName string, options *armcompute.SharedGalleryImagesClientListOptions) clients.SharedGalleryImagesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", location, galleryUniqueName, options)
	ret0, _ := ret[0].(clients.SharedGalleryImagesPager)
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockSharedGalleryImagesClientMockRecorder) NewListPager(location, galleryUniqueName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockSharedGalleryImagesClient)(nil).NewListPager), location, galleryUniqueName, options)
}
