// Code generated by MockGen. DO NOT EDIT.
// Source: private-dns-zones-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_private_dns_zones_client.go -package=mocks -source=private-dns-zones-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armprivatedns "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockPrivateDNSZonesClient is a mock of PrivateDNSZonesClient interface.
type MockPrivateDNSZonesClient struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDNSZonesClientMockRecorder
	isgomock struct{}
}

// MockPrivateDNSZonesClientMockRecorder is the mock recorder for MockPrivateDNSZonesClient.
type MockPrivateDNSZonesClientMockRecorder struct {
	mock *MockPrivateDNSZonesClient
}

// NewMockPrivateDNSZonesClient creates a new mock instance.
func NewMockPrivateDNSZonesClient(ctrl *gomock.Controller) *MockPrivateDNSZonesClient {
	mock := &MockPrivateDNSZonesClient{ctrl: ctrl}
	mock.recorder = &MockPrivateDNSZonesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDNSZonesClient) EXPECT() *MockPrivateDNSZonesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPrivateDNSZonesClient) Get(ctx context.Context, resourceGroupName, privateZoneName string, options *armprivatedns.PrivateZonesClientGetOptions) (armprivatedns.PrivateZonesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, privateZoneName, options)
	ret0, _ := ret[0].(armprivatedns.PrivateZonesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPrivateDNSZonesClientMockRecorder) Get(ctx, resourceGroupName, privateZoneName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPrivateDNSZonesClient)(nil).Get), ctx, resourceGroupName, privateZoneName, options)
}

// NewListByResourceGroupPager mocks base method.
func (m *MockPrivateDNSZonesClient) NewListByResourceGroupPager(resourceGroupName string, options *armprivatedns.PrivateZonesClientListByResourceGroupOptions) clients.PrivateDNSZonesPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListByResourceGroupPager", resourceGroupName, options)
	ret0, _ := ret[0].(clients.PrivateDNSZonesPager)
	return ret0
}

// NewListByResourceGroupPager indicates an expected call of NewListByResourceGroupPager.
func (mr *MockPrivateDNSZonesClientMockRecorder) NewListByResourceGroupPager(resourceGroupName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListByResourceGroupPager", reflect.TypeOf((*MockPrivateDNSZonesClient)(nil).NewListByResourceGroupPager), resourceGroupName, options)
}
