// Code generated by MockGen. DO NOT EDIT.
// Source: storage-accounts-client.go
//
// Generated by this command:
//
//	mockgen -destination=../shared/mocks/mock_storage_accounts_client.go -package=mocks -source=storage-accounts-client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	armstorage "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/v2"
	clients "github.com/overmindtech/cli/sources/azure/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageAccountsPager is a mock of StorageAccountsPager interface.
type MockStorageAccountsPager struct {
	ctrl     *gomock.Controller
	recorder *MockStorageAccountsPagerMockRecorder
	isgomock struct{}
}

// MockStorageAccountsPagerMockRecorder is the mock recorder for MockStorageAccountsPager.
type MockStorageAccountsPagerMockRecorder struct {
	mock *MockStorageAccountsPager
}

// NewMockStorageAccountsPager creates a new mock instance.
func NewMockStorageAccountsPager(ctrl *gomock.Controller) *MockStorageAccountsPager {
	mock := &MockStorageAccountsPager{ctrl: ctrl}
	mock.recorder = &MockStorageAccountsPagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageAccountsPager) EXPECT() *MockStorageAccountsPagerMockRecorder {
	return m.recorder
}

// More mocks base method.
func (m *MockStorageAccountsPager) More() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "More")
	ret0, _ := ret[0].(bool)
	return ret0
}

// More indicates an expected call of More.
func (mr *MockStorageAccountsPagerMockRecorder) More() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "More", reflect.TypeOf((*MockStorageAccountsPager)(nil).More))
}

// NextPage mocks base method.
func (m *MockStorageAccountsPager) NextPage(ctx context.Context) (armstorage.AccountsClientListByResourceGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPage", ctx)
	ret0, _ := ret[0].(armstorage.AccountsClientListByResourceGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPage indicates an expected call of NextPage.
func (mr *MockStorageAccountsPagerMockRecorder) NextPage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MockStorageAccountsPager)(nil).NextPage), ctx)
}

// MockStorageAccountsClient is a mock of StorageAccountsClient interface.
type MockStorageAccountsClient struct {
	ctrl     *gomock.Controller
	recorder *MockStorageAccountsClientMockRecorder
	isgomock struct{}
}

// MockStorageAccountsClientMockRecorder is the mock recorder for MockStorageAccountsClient.
type MockStorageAccountsClientMockRecorder struct {
	mock *MockStorageAccountsClient
}

// NewMockStorageAccountsClient creates a new mock instance.
func NewMockStorageAccountsClient(ctrl *gomock.Controller) *MockStorageAccountsClient {
	mock := &MockStorageAccountsClient{ctrl: ctrl}
	mock.recorder = &MockStorageAccountsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageAccountsClient) EXPECT() *MockStorageAccountsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorageAccountsClient) Get(ctx context.Context, resourceGroupName, accountName string) (armstorage.AccountsClientGetPropertiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, accountName)
	ret0, _ := ret[0].(armstorage.AccountsClientGetPropertiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageAccountsClientMockRecorder) Get(ctx, resourceGroupName, accountName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageAccountsClient)(nil).Get), ctx, resourceGroupName, accountName)
}

// List mocks base method.
func (m *MockStorageAccountsClient) List(resourceGroupName string) clients.StorageAccountsPager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", resourceGroupName)
	ret0, _ := ret[0].(clients.StorageAccountsPager)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockStorageAccountsClientMockRecorder) List(resourceGroupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorageAccountsClient)(nil).List), resourceGroupName)
}
