root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = ["start"]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main main.go"
delay = 1000
exclude_dir = ["assets", "build", "tmp", "vendor", "test", "testdata"]
exclude_file = ["server/admin/assets/dist.css"]
exclude_regex = [
  "_test\\.go",
  "_templ\\.go",
  "\\.sql\\.go",
  ".*models/(models|copyfrom|db).go",
]
exclude_unchanged = false
follow_symlink = false
full_bin = "dlv exec --accept-multiclient --continue --headless --listen :9089 --api-version 2 ./tmp/main --"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "sql", "css", "md"]
include_file = ["sqlc.yaml"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
