package shared

import "github.com/overmindtech/cli/sources/shared"

var (
	ComputeInstance                                                      = shared.NewItemType(GCP, Compute, Instance)
	ComputeInstanceTemplate                                              = shared.NewItemType(GCP, Compute, InstanceTemplate)
	ComputeMachineImage                                                  = shared.NewItemType(GCP, Compute, MachineImage)
	ComputeInstanceGroupManager                                          = shared.NewItemType(GCP, Compute, InstanceGroupManager)
	ComputeSubnetwork                                                    = shared.NewItemType(GCP, Compute, Subnetwork)
	ComputeNetwork                                                       = shared.NewItemType(GCP, Compute, Network)
	ComputeImage                                                         = shared.NewItemType(GCP, Compute, Image)
	ComputeDisk                                                          = shared.NewItemType(GCP, Compute, Disk)
	ComputeDiskType                                                      = shared.NewItemType(GCP, Compute, DiskType)
	ComputeAutoscaler                                                    = shared.NewItemType(GCP, Compute, Autoscaler)
	ComputeResourcePolicy                                                = shared.NewItemType(GCP, Compute, ResourcePolicy)
	ComputeSnapshot                                                      = shared.NewItemType(GCP, Compute, Snapshot)
	ComputeInstanceGroup                                                 = shared.NewItemType(GCP, Compute, InstanceGroup)
	ComputeFirewall                                                      = shared.NewItemType(GCP, Compute, Firewall)
	ComputeRoute                                                         = shared.NewItemType(GCP, Compute, Route)
	ComputeAddress                                                       = shared.NewItemType(GCP, Compute, Address)
	ComputeInstantSnapshot                                               = shared.NewItemType(GCP, Compute, InstantSnapshot)
	ComputeReservation                                                   = shared.NewItemType(GCP, Compute, Reservation)
	ComputeHealthCheck                                                   = shared.NewItemType(GCP, Compute, HealthCheck)
	ComputeHttpHealthCheck                                               = shared.NewItemType(GCP, Compute, HttpHealthCheck)
	ComputeNodeGroup                                                     = shared.NewItemType(GCP, Compute, NodeGroup)
	ComputeNodeTemplate                                                  = shared.NewItemType(GCP, Compute, NodeTemplate)
	ComputeBackendService                                                = shared.NewItemType(GCP, Compute, BackendService)
	ComputeBackendBucket                                                 = shared.NewItemType(GCP, Compute, BackendBucket)
	ComputeSecurityPolicy                                                = shared.NewItemType(GCP, Compute, SecurityPolicy)
	NetworkSecurityClientTlsPolicy                                       = shared.NewItemType(GCP, NetworkSecurity, ClientTlsPolicy)
	NetworkServicesServiceLbPolicy                                       = shared.NewItemType(GCP, NetworkServices, ServiceLbPolicy)
	NetworkServicesServiceBinding                                        = shared.NewItemType(GCP, NetworkServices, ServiceBinding)
	ComputeForwardingRule                                                = shared.NewItemType(GCP, Compute, ForwardingRule)
	ComputeGlobalForwardingRule                                          = shared.NewItemType(GCP, Compute, GlobalForwardingRule)
	ComputeUrlMap                                                        = shared.NewItemType(GCP, Compute, UrlMap)
	ComputeTargetPool                                                    = shared.NewItemType(GCP, Compute, TargetPool)
	ComputeLicense                                                       = shared.NewItemType(GCP, Compute, License)
	CloudKMSCryptoKeyVersion                                             = shared.NewItemType(GCP, CloudKMS, CryptoKeyVersion)
	ComputeRegionCommitment                                              = shared.NewItemType(GCP, Compute, RegionCommitment)
	ComputeAcceleratorType                                               = shared.NewItemType(GCP, Compute, AcceleratorType)
	ComputeRule                                                          = shared.NewItemType(GCP, Compute, Rule)
	IAMServiceAccountKey                                                 = shared.NewItemType(GCP, IAM, ServiceAccountKey)
	IAMServiceAccount                                                    = shared.NewItemType(GCP, IAM, ServiceAccount)
	BigQueryTable                                                        = shared.NewItemType(GCP, BigQuery, Table)
	BigQueryDataset                                                      = shared.NewItemType(GCP, BigQuery, Dataset)
	BigQueryDataTransferTransferConfig                                   = shared.NewItemType(GCP, BigQueryDataTransfer, TransferConfig)
	BigQueryDataTransferTransferRun                                      = shared.NewItemType(GCP, BigQueryDataTransfer, TransferRun)
	BigQueryDataTransferDataSource                                       = shared.NewItemType(GCP, BigQueryDataTransfer, DataSource)
	BigQueryRoutine                                                      = shared.NewItemType(GCP, BigQuery, Routine)
	StorageTransferTransferJob                                           = shared.NewItemType(GCP, StorageTransfer, TransferJob)
	StorageTransferTransferOperation                                     = shared.NewItemType(GCP, StorageTransfer, TransferOperation) // https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferOperations/get
	StorageTransferAgentPool                                             = shared.NewItemType(GCP, StorageTransfer, AgentPool)         // https://cloud.google.com/storage-transfer/docs/reference/rest/v1/projects.agentPools/get
	PubSubSubscription                                                   = shared.NewItemType(GCP, PubSub, Subscription)
	PubSubTopic                                                          = shared.NewItemType(GCP, PubSub, Topic)
	PubSubSchema                                                         = shared.NewItemType(GCP, PubSub, Schema)
	CloudResourceManagerProject                                          = shared.NewItemType(GCP, CloudResourceManager, Project)
	CloudResourceManagerFolder                                           = shared.NewItemType(GCP, CloudResourceManager, Folder)
	CloudResourceManagerOrganization                                     = shared.NewItemType(GCP, CloudResourceManager, Organization)
	CloudKMSKeyRing                                                      = shared.NewItemType(GCP, CloudKMS, KeyRing)
	IAMPolicy                                                            = shared.NewItemType(GCP, IAM, Policy)
	ComputeInstanceSettings                                              = shared.NewItemType(GCP, Compute, InstanceSettings)
	ComputeProject                                                       = shared.NewItemType(GCP, Compute, Project)
	StorageBucket                                                        = shared.NewItemType(GCP, Storage, Bucket)
	StorageBucketAccessControl                                           = shared.NewItemType(GCP, Storage, BucketAccessControl)
	StorageDefaultObjectAccessControl                                    = shared.NewItemType(GCP, Storage, DefaultObjectAccessControl)
	StorageNotificationConfig                                            = shared.NewItemType(GCP, Storage, NotificationConfig)
	ComputeNetworkAttachment                                             = shared.NewItemType(GCP, Compute, NetworkAttachment)
	ComputeStoragePool                                                   = shared.NewItemType(GCP, Compute, StoragePool)
	ComputeStoragePoolType                                               = shared.NewItemType(GCP, Compute, StoragePoolType)
	ComputeZone                                                          = shared.NewItemType(GCP, Compute, Zone)
	ComputeRegion                                                        = shared.NewItemType(GCP, Compute, Region)
	ComputeVpnTunnel                                                     = shared.NewItemType(GCP, Compute, VpnTunnel)
	ComputeNetworkPeering                                                = shared.NewItemType(GCP, Compute, NetworkPeering)
	ComputeGateway                                                       = shared.NewItemType(GCP, Compute, Gateway)
	AIPlatformCustomJob                                                  = shared.NewItemType(GCP, AIPlatform, CustomJob)
	AIPlatformPipelineJob                                                = shared.NewItemType(GCP, AIPlatform, PipelineJob)
	IAMRole                                                              = shared.NewItemType(GCP, IAM, Role)
	BigTableAdminAppProfile                                              = shared.NewItemType(GCP, BigTableAdmin, AppProfile)
	BigTableAdminBackup                                                  = shared.NewItemType(GCP, BigTableAdmin, Backup)
	BigTableAdminTable                                                   = shared.NewItemType(GCP, BigTableAdmin, Table)
	CloudBuildBuild                                                      = shared.NewItemType(GCP, CloudBuild, Build)
	DataplexEntryGroup                                                   = shared.NewItemType(GCP, DataPlex, EntryGroup)
	DataplexAspectType                                                   = shared.NewItemType(GCP, DataPlex, AspectType)
	DataplexDataScan                                                     = shared.NewItemType(GCP, DataPlex, DataScan)
	DataplexEntity                                                       = shared.NewItemType(GCP, DataPlex, Entity)
	ServiceUsageService                                                  = shared.NewItemType(GCP, ServiceUsage, Service)
	RunRevision                                                          = shared.NewItemType(GCP, Run, Revision)
	SQLAdminBackup                                                       = shared.NewItemType(GCP, SqlAdmin, Backup)
	SQLAdminBackupRun                                                    = shared.NewItemType(GCP, SqlAdmin, BackupRun)
	SQLAdminDatabase                                                     = shared.NewItemType(GCP, SqlAdmin, Database)
	SQLAdminUser                                                         = shared.NewItemType(GCP, SqlAdmin, User)
	SQLAdminSSLCert                                                      = shared.NewItemType(GCP, SqlAdmin, SSLCertificate)
	MonitoringCustomDashboard                                            = shared.NewItemType(GCP, Monitoring, CustomDashboard)
	MonitoringNotificationChannel                                        = shared.NewItemType(GCP, Monitoring, NotificationChannel)
	ArtifactRegistryDockerImage                                          = shared.NewItemType(GCP, ArtifactRegistry, DockerImage)
	ArtifactRegistryPackage                                              = shared.NewItemType(GCP, ArtifactRegistry, Package)        // https://cloud.google.com/artifact-registry/docs/reference/rest/v1/projects.locations.repositories.packages/get
	ArtifactRegistryPackageVersion                                       = shared.NewItemType(GCP, ArtifactRegistry, PackageVersion) // https://cloud.google.com/artifact-registry/docs/reference/rest/v1/projects.locations.repositories.packages.versions/get
	ArtifactRegistryPackageTag                                           = shared.NewItemType(GCP, ArtifactRegistry, PackageTag)     // https://cloud.google.com/artifact-registry/docs/reference/rest/v1/projects.locations.repositories.packages.tags/get
	DataformRepository                                                   = shared.NewItemType(GCP, Dataform, Repository)
	DataformCompilationResult                                            = shared.NewItemType(GCP, Dataform, CompilationResult)
	DataformWorkspace                                                    = shared.NewItemType(GCP, Dataform, Workspace)
	DataformWorkflowInvocation                                           = shared.NewItemType(GCP, Dataform, WorkflowInvocation)
	ServiceDirectoryEndpoint                                             = shared.NewItemType(GCP, ServiceDirectory, Endpoint)
	DNSManagedZone                                                       = shared.NewItemType(GCP, DNS, ManagedZone)
	CloudBillingBillingInfo                                              = shared.NewItemType(GCP, CloudBilling, BillingInfo)
	EssentialContactsContact                                             = shared.NewItemType(GCP, EssentialContacts, Contact)
	LoggingSavedQuery                                                    = shared.NewItemType(GCP, Logging, SavedQuery)
	LoggingBucket                                                        = shared.NewItemType(GCP, Logging, Bucket)
	LoggingLink                                                          = shared.NewItemType(GCP, Logging, Link)
	LoggingSink                                                          = shared.NewItemType(GCP, Logging, Sink)
	CloudKMSCryptoKey                                                    = shared.NewItemType(GCP, CloudKMS, CryptoKey)
	CloudKMSImportJob                                                    = shared.NewItemType(GCP, CloudKMS, ImportJob)
	NetworkConnectivityHub                                               = shared.NewItemType(GCP, NetworkConnectivity, Hub)
	NetworkConnectivityInternalRange                                     = shared.NewItemType(GCP, NetworkConnectivity, InternalRange) // https://cloud.google.com/network-connectivity/docs/reference/networkconnectivity/rest/v1/projects.locations.internalRanges/get
	ComputeFirewallPolicy                                                = shared.NewItemType(GCP, Compute, FirewallPolicy)
	AIPlatformTensorBoard                                                = shared.NewItemType(GCP, AIPlatform, TensorBoard)
	AIPlatformExperiment                                                 = shared.NewItemType(GCP, AIPlatform, Experiment)
	AIPlatformExperimentRun                                              = shared.NewItemType(GCP, AIPlatform, ExperimentRun)
	AIPlatformModel                                                      = shared.NewItemType(GCP, AIPlatform, Model)
	AIPlatformEndpoint                                                   = shared.NewItemType(GCP, AIPlatform, Endpoint)
	AIPlatformModelDeploymentMonitoringJob                               = shared.NewItemType(GCP, AIPlatform, ModelDeploymentMonitoringJob)
	AIPlatformBatchPredictionJob                                         = shared.NewItemType(GCP, AIPlatform, BatchPredictionJob)
	AIPlatformSchedule                                                   = shared.NewItemType(GCP, AIPlatform, Schedule)
	AIPlatformDeploymentResourcePool                                     = shared.NewItemType(GCP, AIPlatform, DeploymentResourcePool)
	AIPlatformPersistentResource                                         = shared.NewItemType(GCP, AIPlatform, PersistentResource)
	BigQueryConnection                                                   = shared.NewItemType(GCP, BigQuery, Connection)
	BigTableAdminCluster                                                 = shared.NewItemType(GCP, BigTableAdmin, Cluster)
	CloudBuildTrigger                                                    = shared.NewItemType(GCP, CloudBuild, Trigger)
	RunService                                                           = shared.NewItemType(GCP, Run, Service)
	RunWorkerPool                                                        = shared.NewItemType(GCP, Run, WorkerPool)
	EventarcTrigger                                                      = shared.NewItemType(GCP, Eventarc, Trigger)
	EventarcChannel                                                      = shared.NewItemType(GCP, Eventarc, Channel)            // https://cloud.google.com/eventarc/docs/reference/rest/v1/projects.locations.channels/get
	WorkflowsWorkflow                                                    = shared.NewItemType(GCP, Workflows, Workflow)          // https://cloud.google.com/workflows/docs/reference/rest/v1/projects.locations.workflows/get
	VPCAccessConnector                                                   = shared.NewItemType(GCP, VPCAccess, Connector)         // https://cloud.google.com/vpc/docs/reference/vpcaccess/rest/v1/projects.locations.connectors/get
	SQLAdminInstance                                                     = shared.NewItemType(GCP, SqlAdmin, Instance)           // https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/instances/get
	CloudBillingBillingAccount                                           = shared.NewItemType(GCP, CloudBilling, BillingAccount) // https://cloud.google.com/billing/docs/reference/rest/v1/billingAccounts/get
	ContainerCluster                                                     = shared.NewItemType(GCP, Container, Cluster)           // https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters/get
	ContainerNodePool                                                    = shared.NewItemType(GCP, Container, NodePool)
	ServiceDirectoryNamespace                                            = shared.NewItemType(GCP, ServiceDirectory, Namespace)  // https://cloud.google.com/service-directory/docs/reference/rest/v1/projects.locations.namespaces/get
	SecretManagerSecret                                                  = shared.NewItemType(GCP, SecretManager, Secret)        //https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets/get
	SecretManagerSecretVersion                                           = shared.NewItemType(GCP, SecretManager, SecretVersion) // https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/get
	CloudKMSEKMConnection                                                = shared.NewItemType(GCP, CloudKMS, EKMConnection)      // https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.ekmConnections/get
	ComputeRegionInstanceTemplate                                        = shared.NewItemType(GCP, Compute, RegionalInstanceTemplate)
	BigTableAdminInstance                                                = shared.NewItemType(GCP, BigTableAdmin, Instance)
	ServiceDirectoryService                                              = shared.NewItemType(GCP, ServiceDirectory, Service)
	ArtifactRegistryRepository                                           = shared.NewItemType(GCP, ArtifactRegistry, Repository) // https://cloud.google.com/artifact-registry/docs/reference/rest/v1/projects.locations.repositories/get?rep_location=global
	SpannerDatabase                                                      = shared.NewItemType(GCP, Spanner, Database)            // https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases/get
	SpannerInstance                                                      = shared.NewItemType(GCP, Spanner, Instance)
	SpannerInstanceConfig                                                = shared.NewItemType(GCP, Spanner, InstanceConfig)
	SpannerBackup                                                        = shared.NewItemType(GCP, Spanner, Backup)
	SpannerBackupSchedule                                                = shared.NewItemType(GCP, Spanner, BackupSchedule)    // https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases.backupSchedules/get
	SpannerDatabaseRole                                                  = shared.NewItemType(GCP, Spanner, DatabaseRole)      // https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases.databaseRoles/list
	SpannerDatabaseOperation                                             = shared.NewItemType(GCP, Spanner, DatabaseOperation) // https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases.operations/get
	SpannerSession                                                       = shared.NewItemType(GCP, Spanner, Session)           // https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases.sessions/get
	SpannerInstancePartition                                             = shared.NewItemType(GCP, Spanner, InstancePartition) // https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.instancePartitions/get
	BigQueryModel                                                        = shared.NewItemType(GCP, BigQuery, Model)
	ComputeRegionBackendService                                          = shared.NewItemType(GCP, Compute, RegionBackendService)
	ComputeNetworkEndpointGroup                                          = shared.NewItemType(GCP, Compute, NetworkEndpointGroup)
	ComputeSSLCertificate                                                = shared.NewItemType(GCP, Compute, SSLCertificate)
	ComputeGlobalAddress                                                 = shared.NewItemType(GCP, Compute, GlobalAddress)
	ComputeVpnGateway                                                    = shared.NewItemType(GCP, Compute, VpnGateway)
	ComputeRouter                                                        = shared.NewItemType(GCP, Compute, Router)
	AppEngineService                                                     = shared.NewItemType(GCP, AppEngine, Service)
	CloudFunctionsFunction                                               = shared.NewItemType(GCP, CloudFunctions, Function)
	CloudResourceManagerTagValue                                         = shared.NewItemType(GCP, CloudResourceManager, TagValue)
	CloudResourceManagerTagKey                                           = shared.NewItemType(GCP, CloudResourceManager, TagKey)
	MonitoringAlertPolicy                                                = shared.NewItemType(GCP, Monitoring, AlertPolicy)
	OrgPolicyPolicy                                                      = shared.NewItemType(GCP, OrgPolicy, Policy)
	DataprocCluster                                                      = shared.NewItemType(GCP, Dataproc, Cluster) // https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.clusters/get
	DataprocAutoscalingPolicy                                            = shared.NewItemType(GCP, Dataproc, AutoscalingPolicy)
	DataprocMetastoreService                                             = shared.NewItemType(GCP, Dataproc, MetastoreService) // https://cloud.google.com/dataproc-metastore/docs/reference/rest/v1/projects.locations.services/get
	ComputeInterconnectAttachment                                        = shared.NewItemType(GCP, Compute, InterconnectAttachment)
	ComputeServiceAttachment                                             = shared.NewItemType(GCP, Compute, ServiceAttachment)
	ComputeTargetHttpsProxy                                              = shared.NewItemType(GCP, Compute, TargetHttpsProxy)
	ComputeSSLPolicy                                                     = shared.NewItemType(GCP, Compute, SSLPolicy)
	ComputeTargetHttpProxy                                               = shared.NewItemType(GCP, Compute, TargetHttpProxy)
	ComputeTargetTcpProxy                                                = shared.NewItemType(GCP, Compute, TargetTcpProxy)
	ComputeTargetSslProxy                                                = shared.NewItemType(GCP, Compute, TargetSslProxy)
	ComputeTargetVpnGateway                                              = shared.NewItemType(GCP, Compute, TargetVpnGateway)
	ComputeTargetInstance                                                = shared.NewItemType(GCP, Compute, TargetInstance)
	ComputePublicDelegatedPrefix                                         = shared.NewItemType(GCP, Compute, PublicDelegatedPrefix)
	ComputePublicAdvertisedPrefix                                        = shared.NewItemType(GCP, Compute, PublicAdvertisedPrefix)
	ComputeExternalVpnGateway                                            = shared.NewItemType(GCP, Compute, ExternalVpnGateway)
	RedisInstance                                                        = shared.NewItemType(GCP, Redis, Instance)                                                        // https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances/get
	SecurityCenterManagementSecurityCenterService                        = shared.NewItemType(GCP, SecurityCenterManagement, SecurityCenterService)                        // https://cloud.google.com/security-command-center/docs/reference/security-center-management/rest/v1/projects.locations.securityCenterServices/get
	SecurityCenterManagementSecurityHealthAnalyticsCustomModule          = shared.NewItemType(GCP, SecurityCenterManagement, SecurityHealthAnalyticsCustomModule)          // https://cloud.google.com/security-command-center/docs/reference/security-center-management/rest/v1/projects.locations.securityHealthAnalyticsCustomModules/get
	SecurityCenterManagementEventThreatDetectionCustomModule             = shared.NewItemType(GCP, SecurityCenterManagement, EventThreatDetectionCustomModule)             // https://cloud.google.com/security-command-center/docs/reference/security-center-management/rest/v1/projects.locations.eventThreatDetectionCustomModules/get
	SecurityCenterManagementEffectiveSecurityHealthAnalyticsCustomModule = shared.NewItemType(GCP, SecurityCenterManagement, EffectiveSecurityHealthAnalyticsCustomModule) // https://cloud.google.com/security-command-center/docs/reference/security-center-management/rest/v1/projects.locations.effectiveSecurityHealthAnalyticsCustomModules/get
	SecurityCenterManagementEffectiveEventThreatDetectionCustomModule    = shared.NewItemType(GCP, SecurityCenterManagement, EffectiveEventThreatDetectionCustomModule)    // https://cloud.google.com/security-command-center/docs/reference/security-center-management/rest/v1/projects.locations.effectiveEventThreatDetectionCustomModules/get
	FileInstance                                                         = shared.NewItemType(GCP, File, Instance)
	FileBackup                                                           = shared.NewItemType(GCP, File, Backup)
	CertificateManagerCertificateMap                                     = shared.NewItemType(GCP, CertificateManager, CertificateMap)
	ComputeRoutePolicy                                                   = shared.NewItemType(GCP, Compute, RoutePolicy)                           // Router Route Policy child resource
	ComputeBgpRoute                                                      = shared.NewItemType(GCP, Compute, BgpRoute)                              // Router BGP Route child resource
	NetworkServicesMesh                                                  = shared.NewItemType(GCP, NetworkServices, Mesh)                          // https://cloud.google.com/service-mesh/docs/reference/network-services/rest/v1/projects.locations.meshes/get
	BinaryAuthorizationPlatformPolicy                                    = shared.NewItemType(GCP, BinaryAuthorization, BinaryAuthorizationPolicy) // https://cloud.google.com/binary-authorization/docs/reference/rest/v1/projects.platforms.policies/get
)
