package shared

import "github.com/overmindtech/cli/sources/shared"

var (
	ComputeInstance                = shared.NewItemType(GCP, Compute, Instance)
	ComputeInstanceTemplate        = shared.NewItemType(GCP, Compute, InstanceTemplate)
	ComputeMachineImage            = shared.NewItemType(GCP, Compute, MachineImage)
	ComputeInstanceGroupManager    = shared.NewItemType(GCP, Compute, InstanceGroupManager)
	ComputeSubnetwork              = shared.NewItemType(GCP, Compute, Subnetwork)
	ComputeNetwork                 = shared.NewItemType(GCP, Compute, Network)
	ComputeImage                   = shared.NewItemType(GCP, Compute, Image)
	ComputeDisk                    = shared.NewItemType(GCP, Compute, Disk)
	ComputeDiskType                = shared.NewItemType(GCP, Compute, Disk)
	ComputeAutoscaler              = shared.NewItemType(GCP, Compute, Autoscaler)
	ComputeResourcePolicy          = shared.NewItemType(GCP, Compute, ResourcePolicy)
	ComputeSnapshot                = shared.NewItemType(GCP, Compute, Snapshot)
	ComputeInstanceGroup           = shared.NewItemType(GCP, Compute, InstanceGroup)
	ComputeFirewall                = shared.NewItemType(GCP, Compute, Firewall)
	ComputeRoute                   = shared.NewItemType(GCP, Compute, Route)
	ComputeAddress                 = shared.NewItemType(GCP, Compute, Address)
	ComputeInstantSnapshot         = shared.NewItemType(GCP, Compute, InstantSnapshot)
	ComputeReservation             = shared.NewItemType(GCP, Compute, Reservation)
	ComputeHealthCheck             = shared.NewItemType(GCP, Compute, HealthCheck)
	ComputeNodeGroup               = shared.NewItemType(GCP, Compute, NodeGroup)
	ComputeNodeTemplate            = shared.NewItemType(GCP, Compute, NodeTemplate)
	ComputeBackendService          = shared.NewItemType(GCP, Compute, BackendService)
	ComputeSecurityPolicy          = shared.NewItemType(GCP, Compute, SecurityPolicy)
	NetworkSecurityClientTlsPolicy = shared.NewItemType(GCP, NetworkSecurity, ClientTlsPolicy)
	NetworkServicesServiceLbPolicy = shared.NewItemType(GCP, NetworkServices, ServiceLbPolicy)
	NetworkServicesServiceBinding  = shared.NewItemType(GCP, NetworkServices, ServiceBinding)
	ComputeForwardingRule          = shared.NewItemType(GCP, Compute, ForwardingRule)
	ComputeTargetPool              = shared.NewItemType(GCP, Compute, TargetPool)
	ComputeLicense                 = shared.NewItemType(GCP, Compute, License)
	ComputeMachineType             = shared.NewItemType(GCP, Compute, MachineType)
	CloudKMSCryptoKeyVersion       = shared.NewItemType(GCP, CloudKMS, CryptoKeyVersion)
	ComputeRegionCommitment        = shared.NewItemType(GCP, Compute, RegionCommitment)
	ComputeAcceleratorType         = shared.NewItemType(GCP, Compute, AcceleratorType)
	ComputeRule                    = shared.NewItemType(GCP, Compute, Rule)
	IAMServiceAccountKey           = shared.NewItemType(GCP, IAM, ServiceAccountKey)
	IAMServiceAccount              = shared.NewItemType(GCP, IAM, ServiceAccount)
)
