package shared

import (
	"github.com/overmindtech/cli/sources/shared"
)

const GCP shared.Source = "gcp"

// APIs
const (
	Compute              shared.API = "compute"
	Container            shared.API = "container"
	NetworkSecurity      shared.API = "network-security"
	NetworkServices      shared.API = "network-services"
	CloudKMS             shared.API = "cloud-kms"
	IAM                  shared.API = "iam"
	BigQuery             shared.API = "big-query"
	PubSub               shared.API = "pub-sub"
	CloudResourceManager shared.API = "cloud-resource-manager"
)

// Resources
const (
	Instance                 shared.Resource = "instance"
	Cluster                  shared.Resource = "cluster"
	Disk                     shared.Resource = "disk"
	Network                  shared.Resource = "network"
	NodeGroup                shared.Resource = "node-group"
	NodeTemplate             shared.Resource = "node-template"
	Subnetwork               shared.Resource = "subnetwork"
	Address                  shared.Resource = "address"
	ForwardingRule           shared.Resource = "forwarding-rule"
	BackendService           shared.Resource = "backend-service"
	Autoscaler               shared.Resource = "autoscaler"
	InstanceGroupManager     shared.Resource = "instance-group-manager"
	SecurityPolicy           shared.Resource = "security-policy"
	ClientTlsPolicy          shared.Resource = "client-tls-policy"
	ServiceLbPolicy          shared.Resource = "service-lb-policy"
	ServiceBinding           shared.Resource = "service-binding"
	InstanceTemplate         shared.Resource = "instance-template"
	RegionalInstanceTemplate shared.Resource = "regional-instance-template"
	InstanceGroup            shared.Resource = "instance-group"
	TargetPool               shared.Resource = "target-pool"
	ResourcePolicy           shared.Resource = "resource-policy"
	HealthCheck              shared.Resource = "health-check"
	RegionCommitment         shared.Resource = "region-commitment"
	Reservation              shared.Resource = "reservation"
	MachineType              shared.Resource = "machine-type"
	AcceleratorType          shared.Resource = "accelerator-type"
	Rule                     shared.Resource = "security-policy-rule"
	InstantSnapshot          shared.Resource = "instant-snapshot"
	Image                    shared.Resource = "image"
	Snapshot                 shared.Resource = "snapshot"
	License                  shared.Resource = "license"
	CryptoKeyVersion         shared.Resource = "crypto-key-version"
	DiskType                 shared.Resource = "disk-type"
	MachineImage             shared.Resource = "machine-image"
	Zone                     shared.Resource = "zone"
	Firewall                 shared.Resource = "firewall"
	Route                    shared.Resource = "route"
	ServiceAccountKey        shared.Resource = "service-account-key"
	ServiceAccount           shared.Resource = "service-account"
	Table                    shared.Resource = "table"
	Dataset                  shared.Resource = "dataset"
	Subscription             shared.Resource = "subscription"
	Topic                    shared.Resource = "topic"
	Project                  shared.Resource = "project"
	KeyRing                  shared.Resource = "key-ring"
	CryptoKey                shared.Resource = "crypto-key"
	Policy                   shared.Resource = "policy"
)
