name: Go Init
description: Initializes go and runs go generate
inputs:
  cache:  # id of input
    description: 'Whether to cache go code'
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
        check-latest: true
        cache: ${{ inputs.cache }}

    - name: Get deps and refresh generated code
      shell: bash
      run: |
        go get -v -t -d ./...
        go generate ./...
