apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "overmind-kube-source.clusterRoleBindingName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "overmind-kube-source.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "overmind-kube-source.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
