{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "overmind-kube-source.fullname" . }}
  labels:
    {{- include "overmind-kube-source.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "overmind-kube-source.selectorLabels" . | nindent 6 }}
{{- end }}
