{{- if .Values.source.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overmind-kube-source.fullname" . }}-secrets
type: Opaque
data:
  API_KEY: {{ .Values.source.apiKey.value | b64enc }}
{{- end }}
