apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "overmind-kube-source.serviceAccountName" . }}
  labels:
    {{- include "overmind-kube-source.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
