name: goreleaser-release

on:
  push:
    tags:
      - 'v*'
jobs:
  test:
    name: Run Tests
    runs-on: depot-ubuntu-22.04-4

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
          check-latest: true
          cache: true

      - name: Go Test
        run: |
          go run main.go --version
          go test -race -v -timeout 5m github.com/overmindtech/cli github.com/overmindtech/cli/tfutils

  # Actually release the binaries including signing them
  release:
    runs-on: depot-ubuntu-22.04-32
    if: ${{ github.event_name != 'pull_request' }}
    needs: test
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
          check-latest: true
          cache: true

      - name: Run GoReleaser (publish)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Used to create PRs on the Winget repo
          WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}

      - name: Install cloudsmith CLI
        run: |
          pip install --upgrade cloudsmith-cli

      - name: Upload packages to cloudsmith
        run: |
          for i in dist/*.apk; do
            cloudsmith push alpine overmind/tools/alpine/any-version $i
          done
          for i in dist/*.deb; do
            cloudsmith push deb overmind/tools/any-distro/any-version $i
          done
          for i in dist/*.rpm; do
            cloudsmith push rpm overmind/tools/any-distro/any-version $i
          done
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
