name: goreleaser-dry-run

on:
  pull_request:
jobs:
  dry-run:
    runs-on: depot-ubuntu-22.04-8
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Go Init
        uses: ./.github/actions/go_init

      - run: go run main.go --version

      - name: Run GoReleaser (dry run)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --snapshot --skip publish,sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
